# GitHub Labels Configuration
# This file defines the labels that will be created/synced in the repository

# Priority Labels
- name: priority/high
  color: d73a4a
  description: High priority issues that need immediate attention
- name: priority/medium
  color: fbca04
  description: Medium priority issues
- name: priority/low
  color: 7057ff
  description: Low priority issues

# Type Labels
- name: bug
  color: d73a4a
  description: Something isn't working
- name: enhancement
  color: a2eeef
  description: New feature or request
- name: feature
  color: a2eeef
  description: New feature implementation
- name: question
  color: d876e3
  description: General question
- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation
- name: maintenance
  color: fef2c0
  description: Maintenance tasks and refactoring

# Status Labels
- name: status/in-progress
  color: ff8c00
  description: Currently being worked on
- name: status/review-needed
  color: 5319e7
  description: Awaiting review
- name: status/approved
  color: 0e8a16
  description: Approved and ready to merge
- name: status/blocked
  color: b60205
  description: Blocked by something
- name: status/duplicate
  color: cccccc
  description: Duplicate of another issue
- name: status/wontfix
  color: cccccc
  description: Won't be fixed
- name: status/help-wanted
  color: 008672
  description: Community help needed

# Size Labels
- name: size/XS
  color: 7057ff
  description: Extra small change (0-10 lines)
- name: size/S
  color: 7057ff
  description: Small change (10-30 lines)
- name: size/M
  color: 7057ff
  description: Medium change (30-100 lines)
- name: size/L
  color: 7057ff
  description: Large change (100-500 lines)
- name: size/XL
  color: 7057ff
  description: Extra large change (500+ lines)

# Component Labels
- name: component/ui
  color: 84b6eb
  description: UI components and styling
- name: component/api
  color: 84b6eb
  description: API related changes
- name: component/auth
  color: 84b6eb
  description: Authentication and authorization
- name: component/blog
  color: 84b6eb
  description: Blog functionality
- name: component/admin
  color: 84b6eb
  description: Admin panel features
- name: component/seo
  color: 84b6eb
  description: SEO and metadata

# Technology Labels
- name: nextjs
  color: 000000
  description: Next.js related changes
- name: react
  color: 61dafb
  description: React related changes
- name: typescript
  color: 3178c6
  description: TypeScript related changes
- name: tailwind
  color: 38b2ac
  description: Tailwind CSS related changes
- name: accessibility
  color: 0052cc
  description: Accessibility improvements
- name: performance
  color: 1d76db
  description: Performance optimizations
- name: security
  color: ee0701
  description: Security related changes

# Deployment Labels
- name: deployment/production
  color: c2e0c6
  description: Production deployment
- name: deployment/staging
  color: c2e0c6
  description: Staging deployment
- name: deployment/vercel
  color: c2e0c6
  description: Vercel deployment

# Educational Context Labels
- name: greek-language
  color: 0366d6
  description: Greek language features
- name: literature
  color: 0366d6
  description: Literature related features
- name: education
  color: 0366d6
  description: Educational functionality

# Dependency Labels
- name: dependencies
  color: 0366d6
  description: Dependency updates
- name: npm
  color: 0366d6
  description: npm related changes
- name: github-actions
  color: 0366d6
  description: GitHub Actions workflows

# Quality Labels
- name: good-first-issue
  color: 7057ff
  description: Good for newcomers
- name: hacktoberfest
  color: ff6f69
  description: Hacktoberfest contribution
- name: up-for-grabs
  color: 159957
  description: Available for anyone to work on
