export { AboutContentComponent } from "./about-content";
export { AboutImages } from "./about-images";
export { FloatingIcons } from "./floating-icons";
export { AboutBanner } from "./about-banner";
export { AboutGoals } from "./about-goals";
export { AboutHighlight } from "./about-highlight";
export { AboutFeatures } from "./about-features";
export { AboutHistory } from "./about-history";
export { AboutFacilities } from "./about-facilities";
export { aboutContent, aboutImages, floatingIcons } from "./data";
export { BookIcon, ShieldIcon, StarIcon, TrophyIcon } from "./icons";
export type { AboutContent, AboutImage, FloatingIcon } from "./types";
