export interface Student {
  lastName: string;
  firstName: string;
  schoolTitle: string;
}

export const students2011: Student[] = [
  { lastName: 'ΑΓΓΕΛΗΣ', firstName: 'ΠΑΝΤΕΛΗΣ', schoolTitle: 'ΛΟΓΙΣΤΙΚΗΣ ΤΕΙ ΚΡΗΤΗΣ(ΗΡΑΚΛΕΙΟ)' },
  { lastName: 'ΑΘΑΝΑΣΙΟΥ', firstName: 'ΛΑΜΠΡΙΝΗ', schoolTitle: 'ΦΙΛΟΛΟΓΙΑΣ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'ΒΑΣΙΛΑΚΟΥ', firstName: 'ΚΩΝΣΤΑΝΤΙΝΑ', schoolTitle: 'ΟΡΓΑΝΩΣΗΣ & ΔΙΟΙΚ.ΕΠΙΧΕΙΡ.ΟΙΚΟΝ.ΠΑΝ.ΑΘΗΝΑΣ' },
  { lastName: 'ΒΑΣΙΛΕΙΑΔΗΣ', firstName: 'ΧΡΗΣΤΟΣ', schoolTitle: 'ΜΗΧΑΝΙΚΩΝ Η/Υ & ΠΛΗΡΟΦΟΡΙΚΗΣ ΠΑΤΡΑΣ' },
  { lastName: 'ΓΑΡΟΥΦΗΣ', firstName: 'ΜΙΧΑΗΛ', schoolTitle: 'ΙΑΤΡΙΚΗΣ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'ΓΕΩΡΓΙΟΥ', firstName: 'ΑΣΠΑΣΙΑ ΜΑΡΙΑ', schoolTitle: 'ΧΗΜΕΙΑΣ ΠΑΤΡΑΣ' },
  { lastName: 'ΓΚΑΡΤΖΟΝΙΚΑ', firstName: 'ΘΕΟΔΩΡΑ', schoolTitle: 'ΦΥΣΙΚΗΣ ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΓΟΥΛΑ', firstName: 'ΘΕΟΔΩΡΑ', schoolTitle: 'ΛΟΓΙΣΤΙΚΗΣ ΤΕΙ ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΓΡΟΥΜΠΑΣ', firstName: 'ΗΛΙΑΣ', schoolTitle: 'ΜΑΘΗΜΑΤΙΚΩΝ ΠΑΤΡΑΣ' },
  { lastName: 'ΓΩΓΟΣ', firstName: 'ΠΑΥΛΟΣ', schoolTitle: 'ΧΡΗΜ/ΟΙΚΟΝ.& ΕΛΕΓΚΤΙΚΗΣ ΤΕΙ ΗΠΕΙΡΟΥ (ΠΡΕΒΕΖΑ)' },
  { lastName: 'ΔΗΜΗΤΡΙΟΥ', firstName: 'ΘΩΜΑΣ', schoolTitle: 'ΤΕΝΧ.ΠΛΗΡ.&ΤΗΛΕΠ/ΝΙΩΝ ΤΕΙ ΗΠΕΙΡΟΥ(ΑΡΤΑ)' },
  { lastName: 'ΔΗΜΟΤΑΤΣΗ', firstName: 'ΑΡΤΕΜΙΣ', schoolTitle: 'ΛΟΓΙΣΤΙΚΗΣ ΤΕΙ ΗΠΕΙΡΟΥ (ΠΡΕΒΕΖΑ)' },
  { lastName: 'ΔΗΜΟΥ', firstName: 'ΣΟΦΙΑ', schoolTitle: 'ΕΦΑΡΜΟΣΜΕΝΗΣ ΠΛΗΡ.ΜΑΚΕΔΟΝΙΑΣ(ΘΕΣ/ΝΙΚΗ)' },
  { lastName: 'ΔΗΜΟΥ', firstName: 'ΣΟΦΙΑ', schoolTitle: 'ΠΑΙΔΑΓΩΓΙΚΟ ΔΗΜΟΤΙΚΗΣ ΕΚΠ/ΣΗΣ ΠΑΤΡΑΣ' },
  { lastName: 'ΕΥΣΤΡΑΤΙΟΥ', firstName: 'ΔΗΜΗΤΡΙΟΣ', schoolTitle: 'ΦΥΣΙΚΗΣ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'ΖΑΧΑΡΕΛΟΣ', firstName: 'ΕΥΣΤΡΑΤΙΟΣ', schoolTitle: 'ΦΥΣΙΚΗΣ ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΖΑΧΑΡΗΣ', firstName: 'ΔΗΜΗΤΡΙΟΣ', schoolTitle: 'ΜΗΧΑΝΙΚΩΝ Η/Υ & ΠΛΗΡΟΦΟΡΙΚΗΣ ΠΑΤΡΑΣ' },
  { lastName: 'ΖΟΛΩΤΑ', firstName: 'ΠΑΝΑΓΙΩΤΑ', schoolTitle: 'ΕΦΑΡΜ.ΠΛΗΡ.ΔΙΟΙΚ.&ΟΙΚΟΜ.ΤΕΙ ΙΟΝΙΩΝ ΝΗΣΩΝ' },
  { lastName: 'ΖΟΡΜΠΑ', firstName: 'ΛΑΜΠΡΙΝΗ', schoolTitle: 'ΜΗΧΑΝΟΛΟΓΙΑΣ ΤΕΙ ΠΑΤΡΑΣ' },
  { lastName: 'ΘΑΝΑΣΗΣ', firstName: 'ΡΙΖΟΣ', schoolTitle: 'ΟΙΚΟΝΟΜΙΚΩΝ ΕΠΙΣΤΗΜΩΝ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'ΙΣΛΑΜΑΙ', firstName: 'ΚΕΤΡΙΝ', schoolTitle: 'ΔΙΟΙΚΗΣΗΣ ΕΠΙΧΕΙΡΗΣΕΩΝ ΘΡΑΚΗΣ(ΚΟΜΟΤΗΝΗ)' },
  { lastName: 'ΚΑΛΑΜΠΑΚΟΥ', firstName: 'ΑΙΚΑΤΕΡΙΝΗ', schoolTitle: 'ΤΕΧΝ.ΑΝΤΙΡΡΥΠΑΝΣΗΣ ΤΕΙ ΔΥΤ.ΜΑΚΕΔ.(ΚΟΖΑΝΗ)' },
  { lastName: 'ΚΑΛΠΟΥΖΟΣ', firstName: 'ΜΑΡΙΟΣ', schoolTitle: 'ΟΙΚΟΝ.ΕΠΙΣΤ.ΟΙΚΟΝ.ΠΑΝ/ΜΙΟ ΑΘΗΝΑΣ' },
  { lastName: 'ΚΑΡΑΜΠΑΛΗΣ', firstName: 'ΛΑΜΠΡΟΣ', schoolTitle: 'ΕΠΙΧΕΙΡ.ΣΧΕΔ. & ΠΛΗΡ.ΣΥΣΤΗΜ.ΤΕΙ ΠΑΤΡΑΣ' },
  { lastName: 'ΚΑΡΙΝΟΥ', firstName: 'ΛΑΜΠΡΙΝΗ', schoolTitle: 'ΧΡΗΜ/ΟΙΚΟΝ.&ΕΛΕΓΚΤ.ΤΕΙ ΗΠΕΙΡΟΥ (ΠΡΕΒΕΖΑ)' },
  { lastName: 'ΚΑΡΙΠΙΔΗΣ', firstName: 'ΦΩΤΙΟΣ', schoolTitle: 'ΓΕΩΠ.ΙΧΘΥΟΛ.&ΥΔΑΤ.ΠΕΡ/ΛΟΝΤΟΣ ΘΕΣΣΑΛΙΑΣ' },
  { lastName: 'ΚΑΤΣΑΡΟΥ', firstName: 'ΑΙΚΑΤΕΡΙΝΗ', schoolTitle: 'ΕΦΑΡΜ.ΠΛΗΡ.&ΠΟΛΥΜΕΣ. ΤΕΙ ΚΡΗΤΗΣ(ΗΡΑΚΛΕΙΟ)' },
  { lastName: 'ΚΛΑΦΟΥΝΗΣ', firstName: 'ΝΙΚΟΛΑΟΣ', schoolTitle: 'ΓΕΩΠΟΝΙΑΣ ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΚΟΛΙΟΥΛΗΣ', firstName: 'ΚΩΝ/ΝΟΣ', schoolTitle: 'ΦΥΣΙΚΗΣ ΙΩΑΝΝΙΩΝ' },
  { lastName: 'ΚΟΛΙΟΥΛΗΣ', firstName: 'ΣΠΥΡΙΔΩΝ', schoolTitle: 'ΜΑΘΗΜΑΤΙΚΩΝ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'ΚΟΛΟΚΥΘΑΣ', firstName: 'ΒΑΣΙΛΕΙΟΣ', schoolTitle: 'ΠΛΗΡΟΦΟΡΙΚΗΣ ΙΟΝΙΟΥ (ΚΕΡΚΥΡΑ)' },
  { lastName: 'ΚΟΜΠΟΓΙΑΝΝΗΣ', firstName: 'ΑΛΕΞΑΝΔΡΟΣ', schoolTitle: 'ΛΟΓΙΣΤΙΚΗΣ ΤΕΙ ΗΠΕΙΡΟΥ (ΠΡΕΒΕΖΑ)' },
  { lastName: 'ΚΟΤΣΙΑΥΤΗΣ', firstName: 'ΚΩΝ/ΝΟΣ', schoolTitle: 'ΤΟΠΟΓΡΑΦΙΑΣ ΤΕΙ ΑΘΗΝΑΣ' },
  { lastName: 'ΚΟΥΤΣΟΚΕΡΑ', firstName: 'ΓΕΩΡΓΙΑ', schoolTitle: 'ΔΙΑΤΡ.&ΔΙΑΙΤΟΛ. ΤΕΙ ΛΑΡΙΣΑΣ (ΚΑΡΔΙΤΣΑ)' },
  { lastName: 'ΚΟΥΤΣΟΚΕΡΑ', firstName: 'ΚΑΛΛΙΟΠΗ', schoolTitle: 'ΔΙΑΤΡ.&ΔΙΑΙΤΟΛ. ΤΕΙ ΛΑΡΙΣΑΣ (ΚΑΡΔΙΤΣΑ)' },
  { lastName: 'ΚΩΣΤΟΥΛΑ', firstName: 'ΕΥΑΝΘΙΑ', schoolTitle: 'ΧΗΜΕΙΑΣ ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΛΑΠΠΑ', firstName: 'ΠΕΡΣΕΦΟΝΗ', schoolTitle: 'ΤΕΝΧ.ΠΛΗΡ.&ΤΗΛΕΠ/ΝΙΩΝ ΤΕΙ ΗΠΕΙΡΟΥ(ΑΡΤΑ)' },
  { lastName: 'ΜΑΝΟΥ', firstName: 'ΘΕΟΦΑΝΙΑ', schoolTitle: 'ΤΕΝΧ.ΠΛΗΡ.&ΤΗΛΕΠ/ΝΙΩΝ ΤΕΙ ΗΠΕΙΡΟΥ(ΑΡΤΑ)' },
  { lastName: 'ΜΑΝΟΥ', firstName: 'ΠΑΡΑΣΚΕΥΗ', schoolTitle: 'ΜΑΘΗΜΑΤΙΚΩΝ ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΜΕΣΗΜΕΡΗΣ', firstName: 'ΙΩΑΝΝΗΣ', schoolTitle: 'ΜΑΘΗΜΑΤΙΚΩΝ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'ΜΗΤΡΟΠΑΝΟΥ', firstName: 'ΕΥΣΤΑΘΙΑ', schoolTitle: 'ΟΙΚΟΝΟΜΙΚΩΝ ΕΠΙΣΤΗΜΩΝ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'ΜΗΤΣΟΣ', firstName: 'ΓΕΩΡΓΙΟΣ', schoolTitle: 'ΗΛΕΚΤΡΟΛΟΓΙΑΣ ΤΕΙ ΠΑΤΡΑΣ' },
  { lastName: 'ΜΙΧΑΣ', firstName: 'ΑΠΟΣΤΟΛΟΣ', schoolTitle: 'ΔΙΟΙΚΗΣΗΣ ΕΠΙΧΕΙΡΗΣΕΩΝ ΤΕΙ ΠΑΤΡΑΣ' },
  { lastName: 'ΜΠΑΝΤΑΛΟΥΚΑΣ', firstName: 'ΣΤΕΦΑΝΟΣ', schoolTitle: 'ΟΙΚΟΝ.ΕΠΙΣΤ.ΟΙΚΟΝ.ΠΑΝ/ΜΙΟΥ ΑΘΗΝΑΣ' },
  { lastName: 'ΜΠΕΗ', firstName: 'ΕΛΕΝΗ', schoolTitle: 'ΛΟΓΙΣΤΙΚΗΣ ΤΕΙ ΗΠΕΙΡΟΥ(ΠΡΕΒΕΖΑ)' },
  { lastName: 'ΜΠΕΚΙΑΡΗΣ', firstName: 'ΕΥΡΙΠΙΔΗΣ', schoolTitle: 'ΜΑΘΗΜΑΤΙΚΩΝ ΑΘΗΝΑΣ' },
  { lastName: 'ΜΠΙΚΑ', firstName: 'ΕΛΕΥΘΕΡΙΑ', schoolTitle: 'ΒΙΟΛ.ΕΦΑΡΜ.&ΤΕΧΝΟΛΟΓΙΩΝ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'ΜΠΙΝΙΑΚΟΥ', firstName: 'ΦΡΑΝΚΟ', schoolTitle: 'ΜΗΧΑΝΟΛΟΓΙΑΣ ΤΕΙ ΠΕΙΡΑΙΑ' },
  { lastName: 'ΜΠΟΥΡΑΝΤΑ', firstName: 'ΑΙΚΑΤΕΡΙΝΗ', schoolTitle: 'ΟΡΓΑΝ.&ΔΙΟΙΚ.ΕΠΙΧΕΙΡ.ΜΑΚΕΔΟΝΙΑΣ(ΘΕΣ/ΝΙΚΗ)' },
  { lastName: 'ΜΠΟΥΡΑΣ', firstName: 'ΓΕΩΡΓΙΟΣ', schoolTitle: 'ΑΣΤΥΦΥΛΑΚΩΝ' },
  { lastName: 'ΜΠΟΥΤΗ', firstName: 'ΚΩΝΣΤΑΝΤΙΝΑ', schoolTitle: 'ΦΥΣΙΚΗΣ ΑΘΗΝΑΣ' },
  { lastName: 'ΝΑΤΣΗΣ', firstName: 'ΧΡΗΣΤΟΣ', schoolTitle: 'ΗΛΕΚΤΡ.ΜΗΧ.&ΜΗΧ.Η/Υ ΘΡΑΚΗΣ (ΞΑΝΘΗ)' },
  { lastName: 'ΝΙΚΟΛΑΟΥ', firstName: 'ΝΙΚΟΛΕΤΤΑ', schoolTitle: 'ΛΟΓΙΣΤ.&ΧΡΗΜ/ΟΙΚΟΝ.ΟΙΚΟΝ.ΠΑΝ/ΜΙΟΥ ΑΘΗΝΑΣ' },
  { lastName: 'ΝΤΑΟΥΛΑ', firstName: 'ΠΑΝΑΓΙΩΤΑ', schoolTitle: 'ΟΙΚΟΝΟΜΙΚΩΝ ΕΠΙΣΤΗΜΩΝ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'ΝΤΕΚΟΥΜΕ', firstName: 'ΔΙΟΝΥΣΙΑ', schoolTitle: 'ΓΕΩΛΟΓΙΑΣ ΠΑΤΡΑΣ' },
  { lastName: 'ΞΑΞΙΡΗ', firstName: 'ΝΙΚΟΛΙΝΑ ΑΛΕΞ.', schoolTitle: 'ΔΑΣ/ΓΙΑΣ &ΔΙΑΧ.ΠΕΡ/ΝΤΟΣ&ΦΥΣ.ΠΟΡΩΝ ΘΡΑΚΗ' },
  { lastName: 'ΟΙΚΟΝΟΜΟΥ', firstName: 'ΓΕΩΡΓΙΟΣ', schoolTitle: 'ΓΕΡΜΑΝΙΚΗΣ ΓΛΩΣΣΑΣ & ΦΙΛΟΛ. ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΠΑΠΑΚΙΤΣΟΣ', firstName: 'ΠΑΝΑΓΙΩΤΗΣ', schoolTitle: 'ΜΗΧΑΝΟΛΟΓΙΑΣ ΤΕΙ ΠΑΤΡΑΣ' },
  { lastName: 'ΠΑΠΑΛΕΞΗΣ', firstName: 'ΚΩΝ/ΝΟΣ', schoolTitle: 'ΕΦΑΡΜ.ΠΛΗΡ.ΔΙΟΙΚ.&ΟΙΚ.ΤΕΙ ΔΥΤ.ΜΑΚ.(ΓΡΕΒΕΝΑ)' },
  { lastName: 'ΠΑΠΑΝΑΤΣΙΟΥ', firstName: 'ΓΕΩΡΓΙΑ', schoolTitle: 'ΝΟΣΗΛΕΥΤΙΚΗΣ ΤΕΙ ΗΠΕΙΡΟΥ (ΙΩΑΝΝΙΝΑ)' },
  { lastName: 'ΠΑΠΑΤΣΙΜΠΑΣ', firstName: 'ΓΕΩΡΓΙΟΣ', schoolTitle: 'ΜΗΧΑΝΟΛΟΓΙΑΣ ΤΕΙ ΠΑΤΡΑΣ' },
  { lastName: 'ΠΑΠΟΥΤΣΗΣ', firstName: 'ΒΑΣΙΛΕΙΟΣ', schoolTitle: 'ΟΙΚΟΝ.ΕΠΙΣΤ.ΟΙΚΟΝ.ΠΑΝ/ΜΙΟΥ ΑΘΗΝΑΣ' },
  { lastName: 'ΠΑΠΠΑ', firstName: 'ΝΙΚΟΛΕΤΑ', schoolTitle: 'ΑΓΡΟΝΟΜΩΝ & ΤΟΠΟΓΡΑΦΩΝ ΜΗΧ.ΕΜΠ.' },
  { lastName: 'ΠΑΠΠΑΣ', firstName: 'ΔΗΜΗΤΡΙΟΣ', schoolTitle: 'ΑΣΤΥΦΥΛΑΚΩΝ' },
  { lastName: 'ΠΑΠΠΑΣ', firstName: 'ΚΩΝ/ΝΟΣ', schoolTitle: 'ΟΡΓΑΝ.&ΔΙΟΙΚ.ΕΠΙΧ.ΟΙΚΟΝ.ΠΑΝ/ΜΙΟΥ ΑΘΗΝΑΣ' },
  { lastName: 'ΠΑΡΑΣΚΕΥΑΚΗΣ', firstName: 'ΝΙΚΟΛΑΟΣ', schoolTitle: 'ΠΟΛ.ΕΡΓΩΝ ΥΠΟΔΟΜΗΣ ΤΕΙ ΠΑΤΡΑΣ' },
  { lastName: 'ΠΟΛΥΖΟΥ', firstName: 'ΜΑΡΙΑ', schoolTitle: 'ΜΑΘΗΜΑΤΙΚΩΝ ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΡΕΝΤΖΟΣ', firstName: 'ΠΑΝΑΓΙΩΤΗΣ', schoolTitle: 'ΠΟΛΙΤΙΚΩΝ ΜΗΧΑΝΙΚΩΝ ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΣΑΚΑΓΙΑΝΝΗ', firstName: 'ΚΩΝ/ΝΑ', schoolTitle: 'ΔΗΜΟΣΙΑΣ ΥΓΙΕΙΝΗΣ ΤΕΙ ΑΘΗΝΑΣ' },
  { lastName: 'ΣΑΚΑΓΙΑΝΝΗ', firstName: 'ΜΑΡΙΑΝΘΗ', schoolTitle: 'ΔΗΜΟΣΙΑΣ ΔΙΟΙΚΗΣΗΣ ΠΑΝΤΕΙΟΥ' },
  { lastName: 'ΣΑΚΚΑΣ', firstName: 'ΟΡΕΣΤΗΣ', schoolTitle: 'ΛΟΓΙΣΤΙΚΗΣ ΤΕΙ ΚΑΒΑΛΑΣ' },
  { lastName: 'ΣΑΛΛΑΣ', firstName: 'ΓΕΩΡΓΙΟΣ', schoolTitle: 'ΜΟΝΙΜΩΝ ΥΠΑΞ/ΚΩΝ ΝΑΥΤΙΚΟΥ Σ.Μ.Υ.Ν.' },
  { lastName: 'ΣΚΟΥΦΟΣ', firstName: 'ΣΤΥΛΙΑΝΟΣ', schoolTitle: 'ΚΤΗΝΙΑΤΡΙΚΗΣ ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΣΤΕΦΑΝΟΥ', firstName: 'ΠΑΝΑΓΙΩΤΑ', schoolTitle: 'ΠΟΛΙΤΙΚΩΝ ΜΗΧΑΝΙΚΩΝ ΕΜΠ' },
  { lastName: 'ΤΑΓΚΑ', firstName: 'ΒΑΣΙΛΙΚΗ', schoolTitle: 'ΟΙΚΟΝΟΜΙΚΩΝ ΕΠΙΣΤΗΜΩΝ ΠΑΤΡΑΣ' },
  { lastName: 'ΤΑΤΣΗΣ', firstName: 'ΒΑΣΙΛΕΙΟΣ', schoolTitle: 'ΜΗΝ.ΧΩΡ/ΞΙΑΣ, ΠΟΛΕΟΔ.&ΠΕΡΙΦ.ΑΝΑΠΤ.ΒΟΛΟΥ' },
  { lastName: 'ΤΑΤΣΗΣ', firstName: 'ΦΩΤΙΟΣ', schoolTitle: 'ΔΙΟΙΚ.ΕΠΙΣΤ.& ΤΕΧΝ.ΟΙΚΟΝ.ΠΑΝ/ΜΙΟΥ ΑΘΗΝΑΣ' },
  { lastName: 'ΤΖΙΜΑ', firstName: 'ΕΛΕΝΗ', schoolTitle: 'ΙΑΤΡΙΚΗΣ ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΤΡΟΜΠΟΥΚΗΣ', firstName: 'ΧΡΗΣΤΟΣ', schoolTitle: 'ΕΣΩΤ.ΑΡΧΙΤ/ΚΗΣ, ΔΙΑΚ.&ΣΧΕΔ.ΑΝΤΙΚ.ΤΕΙ ΣΕΡΡΩΝ' },
  { lastName: 'ΤΣΙΟΥΤΣΙΟΣ', firstName: 'ΒΑΣΙΛΕΙΟΣ', schoolTitle: 'ΤΕΝΧ.ΠΛΗΡ.&ΤΗΛΕΠ/ΝΙΩΝ ΤΕΙ ΗΠΕΙΡΟΥ(ΑΡΤΑ)' },
  { lastName: 'ΤΣΙΡΚΑΣ', firstName: 'ΚΩΝ/ΝΟΣ', schoolTitle: 'ΜΗΧ.ΠΛΗΡ.& ΤΗΛΕΠ/ΝΙΩΝ ΔΥΤ.ΜΑΚ.(ΚΟΖΑΝΗ)' },
  { lastName: 'ΤΣΙΡΩΝΗ', firstName: 'ΒΑΣΙΛΙΚΗ', schoolTitle: 'ΧΗΜΕΙΑΣ ΑΘΗΝΑΣ' },
  { lastName: 'ΤΣΙΤΣΙΚΑΣ', firstName: 'ΒΑΣΙΛΕΙΟΣ', schoolTitle: 'ΛΟΓΙΣΤΙΚΗΣ ΤΕΙ ΚΑΒΑΛΑΣ' },
  { lastName: 'ΤΥΡΟΛΟΓΟΣ', firstName: 'ΑΛΕΞΙΟΣ', schoolTitle: 'ΟΙΚΟΝΟΜΙΚΩΝ ΕΠΙΣΤΗΜΩΝ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'ΦΩΤΗ', firstName: 'ΧΡΥΣΑΝΘΗ', schoolTitle: 'ΟΙΚΟΝΟΜΙΚΗΣ ΕΠΙΣΤΗΜΗΣ ΠΕΙΡΑΙΑ' },
  { lastName: 'ΧΑΛΜΑ', firstName: 'ΧΡΙΣΤΙΝΑ', schoolTitle: 'ΙΣΤΟΡΙΑΣ & ΑΡΧΑΙΟΛΟΓΙΑΣ ΑΘΗΝΑΣ' },
  { lastName: 'ΧΗΡΑ', firstName: 'ΠΑΡΑΣΚΕΥΗ', schoolTitle: 'ΠΑΙΔΑΓΩΓΙΚΟ ΝΗΠΙΑΓΩΓΩΝ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'ΧΡΗΣΤΟΠΑΝΟΣ', firstName: 'ΣΕΡΓΙΟΣ', schoolTitle: 'ΓΕΩΠΟΝΙΑΣ ΘΕΣ/ΝΙΚΗΣ' },
];

// Continue with 2012-2016 data...
export const students2012: Student[] = [
  { lastName: 'ΑΘΑΝΑΣΟΠΟΥΛΟΣ', firstName: 'ΚΩΝΣΤΑΝΤΙΝΟΣ', schoolTitle: 'ΑΣΤΥΦΥΛΑΚΩΝ' },
  { lastName: 'ΑΡΑΒΑΝΗ', firstName: 'ΒΑΣΙΛΙΚΗ', schoolTitle: 'ΔΙΑΧ/ΣΗΣ ΠΕΡ/ΝΤΟΣ & ΦΥΣΙΚΩΝ ΠΟΡΩΝ ΔΥΤ.ΕΛΛΑΔΑΣ (ΑΓΡΙΝΙΟ)' },
  { lastName: 'ΑΡΑΒΑΝΗΣ', firstName: 'ΣΑΒΒΑΣ', schoolTitle: 'ΤΕΧΝΟΛΟΓΙΑΣ ΠΛΗΡΟΦΟΡΙΚΗΣ & ΤΗΛΕΠΙΚΟΙΝΩΝΙΩΝ ΤΕΙ ΛΑΡΙΣΑΣ' },
  { lastName: 'ΒΑΓΕΝΑΣ', firstName: 'ΘΕΟΔΩΡΟΣ', schoolTitle: 'ΔΙΟΙΚΗΣΗΣ ΕΠΙΧΕΙΡΗΣΕΩΝ ΠΑΤΡΑΣ' },
  { lastName: 'ΒΑΔΙΒΟΥΛΗΣ', firstName: 'ΘΕΟΧΑΡΗΣ', schoolTitle: 'ΠΟΛ. ΕΡΓΩΝ ΥΠΟΔΟΜΗΣ ΤΕΙ ΠΑΤΡΑΣ' },
  { lastName: 'ΒΑΡΗ', firstName: 'ΕΥΘΑΛΙΑ ΙΣΜΗΝ', schoolTitle: 'ΔΙΕΘΝΩΝ & ΕΥΡΩΠΑΪΚΩΝ ΣΠΟΥΔΩΝ ΠΕΙΡΑΙΑ ΤΡΙΤΕΚΝΟΙ' },
  { lastName: 'ΒΑΣΙΟΥΛΑ', firstName: 'ΑΝΔΡΙΑΝΗ ΙΟΥΛ', schoolTitle: 'ΟΡΓΑΝΩΣΗΣ&ΔΙΟΙΚΗΣΗΣ ΕΠΙΧΕΙΡΗΣΕΩΝ ΜΑΚΕΔΟΝΙΑΣ(ΘΕΣ/ΝΙΚΗ)ΠΟΛΥΤΕΚΝΟΙ' },
  { lastName: 'ΒΑΣΣΟΣ', firstName: 'ΒΑΣΙΛΕΙΟΣ', schoolTitle: 'ΔΙΟΙΚ.ΕΠΙΧ.ΑΓΡ.ΠΡΟΪΟΝΤΩΝ & ΤΡΟΦ.ΔΥΤ.ΕΛΛΑΔ (ΑΓΡΙΝΙΟ)' },
  { lastName: 'ΒΕΛΙΟΣ', firstName: 'ΝΙΚΟΛΑΟΣ ΑΛΕΞ', schoolTitle: 'ΦΥΣΙΚΗΣ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'ΒΛΑΡΑ', firstName: 'ΒΑΛΕΝΤΙΝΑ', schoolTitle: 'ΜΑΘΗΜΑΤΙΚΩΝ ΠΑΤΡΑΣ' },
  { lastName: 'ΒΟΒΛΑΣ', firstName: 'ΚΩΝΣΤΑΝΤΙΝΟΣ', schoolTitle: 'ΛΟΓΙΣΤΙΚΗΣ ΤΕΙ ΗΠΕΙΡΟΥ (ΠΡΕΒΕΖΑ)' },
  { lastName: 'ΓΕΡΟΔΗΜΟΣ', firstName: 'ΒΑΣΙΛΕΙΟΣ', schoolTitle: 'ΗΛΕΚΤΡΟΛΟΓΩΝ ΜΗΧ/ΚΩΝ & ΜΗΧ/ΚΩΝ ΥΠΟΛΟΓΙΣΤΩΝ ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΓΕΩΡΓΑΝΟΣ', firstName: 'ΒΑΣΙΛΕΙΟΣ', schoolTitle: 'ΦΥΤΙΚΗΣ ΠΑΡΑΓΩΓΗΣ ΤΕΙ ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΓΙΩΤΗΣ', firstName: 'ΓΕΩΡΓΙΟΣ', schoolTitle: 'ΟΙΚΟΝΟΜΙΚΩΝ ΕΠΙΣΤΗΜΩΝ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'ΓΙΩΤΗΣ', firstName: 'ΧΡΗΣΤΟΣ', schoolTitle: 'ΟΙΚΟΝΟΜΙΚΩΝ ΕΠΙΣΤΗΜΩΝ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'ΓΚΑΝΑΒΙΑΣ', firstName: 'ΛΑΜΠΡΟΣ', schoolTitle: 'ΗΛΕΚΤΡΟΝΙΚΗΣ ΤΕΙ ΠΕΙΡΑΙΑ ΚΟΙΝ.ΚΡΙΤ.' },
  { lastName: 'ΓΚΑΡΤΖΩΝΗ', firstName: 'ΕΛΛΗ', schoolTitle: 'ΓΕΩΠΛΗΡΟΦΟΡΙΚΗΣ & ΤΟΠΟΓΡΑΦΙΑΣ ΤΕΙ ΣΕΡΡΩΝ' },
  { lastName: 'ΓΟΥΣΙΑ', firstName: 'ΕΥΑΓΓΕΛΙΑ', schoolTitle: 'ΓΕΩΠΟΝΙΑΣ ΙΧΘ/ΓΙΑΣ & ΥΔΑΤΙΝΟΥ ΠΕΡ/ΝΤΟΣ ΘΕΣΣΑΛ (ΒΟΛΟΣ)' },
  { lastName: 'ΔΑΦΝΟΥ', firstName: 'ΕΛΕΥΘΕΡΙΑ', schoolTitle: 'ΟΡΓΑΝΩΣΗΣ & ΔΙΟΙΚΗΣΗΣ ΕΠΙΧΕΙΡΗΣΕΩΝ ΠΕΙΡΑΙΑ ΤΡΙΤΕΚΝΟΙ' },
  { lastName: 'ΔΗΜΗΤΡΙΟΥ', firstName: 'ΛΑΜΠΡΟΣ', schoolTitle: 'ΤΕΧΝΟΛΟΓΙΑΣ ΠΛΗΡΟΦΟΡΙΚΗΣ & ΤΗΛ/ΝΙΩΝ ΤΕΙ ΗΠΕΙΡΟΥ (ΑΡΤΑ)' },
  { lastName: 'ΔΗΜΟΥ', firstName: 'ΣΟΦΙΑ', schoolTitle: 'ΜΗΧΑΝΙΚΩΝ Η/Υ ΚΑΙ ΠΛΗΡΟΦΟΡΙΚΗΣ ΠΑΤΡΑΣ ΤΡΙΤΕΚΝ 2011' },
  { lastName: 'ΕΥΤΑΞΙΑ', firstName: 'ΜΑΡΙΑ', schoolTitle: 'ΜΟΝΙΜΩΝ ΥΠΑΞΙΩΜΑΤΙΚΩΝ ΝΑΥΤΙΚΟΥ Σ.Μ.Υ.Ν.' },
  { lastName: 'ΚΑΚΑΡΙΑΡΗ', firstName: 'ΒΑΣΙΛΙΚΗ', schoolTitle: 'ΕΠΙΣΤ. ΤΗΣ ΠΡΟΣΧ. ΑΓΩΓΗΣ & ΕΚΠ/ΚΟΥ ΣΧΕΔ. ΑΙΓΑΙΟΥ (ΡΟΔΟΣ)' },
  { lastName: 'ΚΑΡΑΚΩΣΤΑΣ', firstName: 'ΘΕΟΦΑΝΗΣ', schoolTitle: 'ΤΕΧΝΟΛΟΓΙΑΣ ΠΛΗΡΟΦΟΡΙΚΗΣ & ΤΗΛ/ΝΙΩΝ ΤΕΙ ΗΠΕΙΡΟΥ (ΑΡΤΑ)' },
  { lastName: 'ΚΑΡΑΜΠΑΛΗΣ', firstName: 'ΛΑΜΠΡΟΣ', schoolTitle: 'ΛΑΙΚΗΣ & ΠΑΡΑΔΟΣΙΑΚΗΣ ΜΟΥΣΙΚΗΣ ΤΕΙ ΗΠΕΙΡΟΥ (ΑΡΤΑΣ) Κ.ΚΡΙΤ 2011' },
  { lastName: 'ΚΑΡΑΜΠΙΝΗΣ', firstName: 'ΣΠΥΡΙΔΩΝ', schoolTitle: 'ΗΛΕΚΤΡΟΝΙΚΗΣ ΤΕΙ ΛΑΜΙΑΣ ΠΟΛΥΤΕΚ.' },
  { lastName: 'ΚΟΛΙΟΥ', firstName: 'ΠΑΡΑΣΚΕΥΗ', schoolTitle: 'ΠΟΛΙΤΙΚΩΝ ΜΗΧΑΝΙΚΩΝ ΘΡΑΚΗΣ (ΞΑΝΘΗ) ΠΟΛΥΤΕΚΝ.' },
  { lastName: 'ΚΟΝΗΣ', firstName: 'ΚΩΝΣΤΑΝΤΙΝΟΣ', schoolTitle: 'ΑΥΤΟΜΑΤΙΣΜΟΥ ΤΕΙ ΜΕΣΟΛΟΓΓΙΟΥ' },
  { lastName: 'ΚΟΝΙΑΡΗ', firstName: 'ΑΓΓΕΛΙΚΗ', schoolTitle: 'ΦΥΣΙΚΗΣ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'ΚΟΝΤΟΧΡΗΣΤΟΣ', firstName: 'ΕΥΑΓΓΕΛΟΣ', schoolTitle: 'ΝΟΣΗΛΕΥΤΙΚΗΣ ΤΕΙ ΗΠΕΙΡΟΥ (ΙΩΑΝΝΙΝΑ)' },
  { lastName: 'ΚΟΤΣΑΡΙΝΗΣ', firstName: 'ΜΙΛΤΙΑΔΗΣ', schoolTitle: 'ΜΗΧΑΝΙΚΩΝ Η/Υ ΚΑΙ ΠΛΗΡΟΦΟΡΙΚΗΣ ΠΑΤΡΑΣ' },
  { lastName: 'ΚΟΤΣΙΑΥΤΗΣ', firstName: 'ΚΩΝΣΤΑΝΤΙΝΟΣ', schoolTitle: 'ΠΟΛ. ΕΡΓΩΝ ΥΠΟΔΟΜΗΣ ΤΕΙ ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΚΟΥΚΟΥ', firstName: 'ΕΛΕΝΗ', schoolTitle: 'ΜΑΘΗΜΑΤΙΚΩΝ ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΚΟΥΦΟΥΛΗΣ', firstName: 'ΑΘΑΝΑΣΙΟΣ', schoolTitle: 'ΠΛΗΡΟΦΟΡΙΚΗΣ & ΤΕΧΝΟΛΟΓΙΑΣ ΥΠΟΛΟΓΙΣΤΩΝ ΤΕΙ ΛΑΜΙΑΣ' },
  { lastName: 'ΚΩΣΤΑ', firstName: 'ΑΛΕΞΑΝΔΡΑ', schoolTitle: 'ΠΟΛΙΤΙΚΩΝ ΜΗΧΑΝΙΚΩΝ ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΛΕΚΟΥ', firstName: 'ΧΑΡΙΤΙΝΗ', schoolTitle: 'ΜΗΧΑΝΙΚΩΝ Η/Υ ΚΑΙ ΠΛΗΡΟΦΟΡΙΚΗΣ ΠΑΤΡΑΣ' },
  { lastName: 'ΛΙΓΚΑΣ', firstName: 'ΑΘΑΝΑΣΙΟΣ', schoolTitle: 'ΛΟΓΙΣΤΙΚΗΣ & ΧΡΗΜΑΤΟΟΙΚΟΝΟΜΙΚΗΣ ΟΙΚΟΝΟΜΙΚΟΥ ΠΑΝ. ΑΘΗΝΑΣ' },
  { lastName: 'ΛΙΝΑΡΔΑΤΟΣ', firstName: 'ΕΛΕΥΘΕΡΙΟΣ', schoolTitle: 'ΜΗΧΑΝΙΚΩΝ ΧΩΡΟΤΑΞΙΑΣ & ΑΝΑΠΤΥΞΗΣ ΘΕΣ/ΝΙΚΗΣ (ΒΕΡΟΙΑ)' },
  { lastName: 'ΛΙΟΝΤΟΣ', firstName: 'ΒΗΣΣΑΡΙΩΝ', schoolTitle: 'ΜΗΧΑΝΟΛΟΓΙΑΣ ΤΕΙ ΚΑΒΑΛΑΣ' },
  { lastName: 'ΜΑΛΑΚΟΥ', firstName: 'ΑΡΧΟΝΤΩ', schoolTitle: 'ΚΤΗΝΙΑΤΡΙΚΗΣ ΘΕΣΣΑΛΙΑΣ (ΚΑΡΔΙΤΣΑ) ΤΡΙΤΕΚΝΟΙ' },
  { lastName: 'ΜΑΛΙΣΙΟΒΑ', firstName: 'ΓΕΩΡΓΙΑ', schoolTitle: 'ΛΟΓΙΣΤΙΚΗΣ & ΧΡΗΜΑΤΟΟΙΚΟΝΟΜΙΚΗΣ ΟΙΚΟΝΟΜΙΚΟΥ ΠΑΝ. ΑΘΗΝΑΣ' },
  { lastName: 'ΜΑΛΤΕΖΟΥ', firstName: 'ΕΡΣΑΓΙΑ', schoolTitle: 'ΝΟΜΙΚΗΣ ΘΡΑΚΗΣ (ΚΟΜΟΤΗΝΗ)' },
  { lastName: 'ΜΑΝΙΦΑΒΑΣ', firstName: 'ΣΩΚΡΑΤΗΣ', schoolTitle: 'ΕΚΠ/ΚΩΝ ΗΛΕΚΤΡΟΝΙΚΗΣ Α.Σ.ΠΑΙΤ.Τ.Ε. ΑΘΗΝΑΣ ΠΟΛΥΤΕΚΝ.' },
  { lastName: 'ΜΙΧΑΣ', firstName: 'ΑΠΟΣΤΟΛΟΣ', schoolTitle: 'ΔΙΟΙΚ.ΕΠΙΧ.ΑΓΡ.ΠΡΟΪΟΝΤΩΝ & ΤΡΟΦ.ΔΥΤ.ΕΛΛΑΔ (ΑΓΡΙΝΙΟ) ΤΡΙΤ2010-11' },
  { lastName: 'ΜΠΑΚΑΓΙΑΝΝΗΣ', firstName: 'ΣΟΦΟΚΛΗΣ', schoolTitle: 'ΤΕΧΝΟΛΟΓΙΑΣ ΠΛΗΡΟΦΟΡΙΚΗΣ & ΤΗΛ/ΝΙΩΝ ΤΕΙ ΗΠΕΙΡΟΥ (ΑΡΤΑ)' },
  { lastName: 'ΜΠΑΡΚΑΣ', firstName: 'ΧΡΗΣΤΟΣ', schoolTitle: 'ΓΕΩΓΡΑΦΙΑΣ ΑΙΓΑΙΟΥ (ΜΥΤΙΛΗΝΗ)' },
  { lastName: 'ΜΠΕΗ', firstName: 'ΕΛΕΝΗ', schoolTitle: 'ΛΟΓΙΣΤΙΚΗΣ ΤΕΙ ΗΠΕΙΡΟΥ (ΠΡΕΒΕΖΑ)' },
  { lastName: 'ΜΠΕΚΙΑΡΗΣ', firstName: 'ΕΥΡΙΠΙΔΗΣ', schoolTitle: 'ΙΑΤΡΙΚΗΣ ΘΡΑΚΗΣ (ΑΛΕΞΑΝΔΡΟΥΠΟΛΗ)' },
  { lastName: 'ΜΠΟΚΟΣ', firstName: 'ΠΥΡΡΟΣ', schoolTitle: 'ΙΑΤΡΙΚΩΝ ΕΡΓΑΣΤΗΡΙΩΝ ΤΕΙ ΑΘΗΝΑΣ ΚΟΙΝ.ΚΡΙΤ.' },
  { lastName: 'ΜΠΟΥΡΑΝΤΑΣ', firstName: 'ΕΥΑΓΓΕΛΟΣ', schoolTitle: 'ΜΟΝΙΜΩΝ ΥΠΑΞΙΩΜΑΤΙΚΩΝ ΣΤΡΑΤΟΥ (Σ.Μ.Υ) - ΟΠΛΑ' },
  { lastName: 'ΝΑΚΑΣ', firstName: 'ΚΩΝΣΤΑΝΤΙΝΟΣ', schoolTitle: 'ΧΗΜΙΚΩΝ ΜΗΧΑΝΙΚΩΝ ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΝΑΚΟΣ', firstName: 'ΕΥΣΤΑΘΙΟΣ', schoolTitle: 'ΤΕΧΝΟΛΟΓΙΑΣ ΠΛΗΡΟΦΟΡΙΚΗΣ & ΤΗΛ/ΝΙΩΝ ΤΕΙ ΗΠΕΙΡΟΥ (ΑΡΤΑ)' },
  { lastName: 'ΝΑΣΗ', firstName: 'ΒΑΣΙΛΙΚΗ', schoolTitle: 'ΟΡΓΑΝΩΣΗΣ & ΔΙΟΙΚΗΣΗΣ ΕΠΙΧΕΙΡΗΣΕΩΝ ΜΑΚΕΔΟΝΙΑΣ (ΘΕΣ/ΝΙΚΗ)' },
  { lastName: 'ΝΙΚΟΛΑΟΥ', firstName: 'ΓΕΩΡΓΙΟΣ', schoolTitle: 'ΝΟΜΙΚΗΣ ΑΘΗΝΑΣ' },
  { lastName: 'ΝΤΑΛΑΟΥΤΗΣ', firstName: 'ΑΝΔΡΕΑΣ', schoolTitle: 'ΜΑΘΗΜΑΤΙΚΩΝ ΑΘΗΝΑΣ' },
  { lastName: 'ΝΤΕΛΗ', firstName: 'ANNA', schoolTitle: 'ΕΠΙΧΕΙΡ/ΚΟΥ ΣΧΕΔΙΑΣΜΟΥ & ΠΛΗΡ/ΚΩΝ ΣΥΣΤΗΜΑΤΩΝ ΤΕΙ ΠΑΤΡΑΣ' },
  { lastName: 'ΟΙΚΟΝΟΜΙΔΗΣ', firstName: 'ΙΩΑΝΝΗΣ', schoolTitle: 'ΧΗΜΕΙΑΣ ΑΘΗΝΑΣ' },
  { lastName: 'ΟΙΚΟΝΟΜΟΥ', firstName: 'ΑΙΚΑΤΕΡΙΝΗ', schoolTitle: 'ΟΡΓΑΝΩΣΗΣ & ΔΙΟΙΚΗΣΗΣ ΕΠΙΧΕΙΡΗΣΕΩΝ ΠΕΙΡΑΙΑ ΠΟΛΥΤΕΚΝ.' },
  { lastName: 'ΟΙΚΟΝΟΜΟΥ', firstName: 'ΒΑΣΙΛΕΙΟΣ', schoolTitle: 'ΦΥΣΙΚΗΣ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'ΠΑΠΑΒΑΓΓΕΛΗΣ', firstName: 'ΑΛΕΞΑΝΔΡΟΣ', schoolTitle: 'ΔΙΟΙΚ.ΕΠΙΧ.ΑΓΡ.ΠΡΟΪΟΝΤΩΝ & ΤΡΟΦ.ΔΥΤ.ΕΛΛΑΔ (ΑΓΡΙΝΙΟ)' },
  { lastName: 'ΠΑΠΑΔΗΜΑ', firstName: 'ΦΩΤΕΙΝΗ', schoolTitle: 'ΤΕΧΝΟΛΟΓΙΑΣ ΠΕΤΡΕΛΑΙΟΥ & ΦΥΣΙΚΟΥ ΑΕΡΙΟΥ ΤΕΙ ΚΑΒΑΛΑΣ' },
  { lastName: 'ΠΑΠΑΔΗΜΑΣ', firstName: 'ΜΙΛΤΙΑΔΗΣ', schoolTitle: 'ΕΠΙΣΤ. ΦΥΣΙΚΗΣ ΑΓΩΓΗΣ & ΑΘΛΗΤΙΣΜΟΥ ΑΘΗΝΑΣ ΠΟΛΥΤΕΚΝ.' },
  { lastName: 'ΠΑΠΑΘΑΝΑΣΙΟΥ', firstName: 'ΔΗΜΗΤΡΙΟΣ', schoolTitle: 'ΤΕΧΝΟΛΟΓΙΑΣ ΠΛΗΡΟΦΟΡΙΚΗΣ & ΤΗΛ/ΝΙΩΝ ΤΕΙ ΗΠΕΙΡΟΥ (ΑΡΤΑ)' },
  { lastName: 'ΠΑΠΑΡΟΥΝΗ', firstName: 'ΛΑΟΥΡΑ', schoolTitle: 'ΜΗΧΑΝΙΚΩΝ ΧΩΡΟΤΑΞΙΑΣ & ΑΝΑΠΤΥΞΗΣ ΘΕΣ/ΝΙΚΗΣ (ΒΕΡΟΙΑ)' },
  { lastName: 'ΠΑΠΑΣΤΑΘΗΣ', firstName: 'ΗΡΑΚΛΗΣ', schoolTitle: 'ΤΕΧΝΟΛΟΓΙΑΣ ΙΑΤΡΙΚΩΝ ΟΡΓΑΝΩΝ ΤΕΙ ΑΘΗΝΑΣ' },
  { lastName: 'ΠΑΠΠΑ', firstName: 'ΝΙΚΟΛΕΤΑ', schoolTitle: 'ΑΡΧΙΤΕΚΤΟΝΩΝ ΜΗΧΑΝΙΚΩΝ ΕΜΠ ΠΟΛΥΤ 2011' },
  { lastName: 'ΠΑΠΠΑ', firstName: 'ΑΡΤΕΜΙΣ', schoolTitle: 'ΓΕΩΠΟΝΙΑΣ ΘΕΣ/ΝΙΚΗΣ ΠΟΛΥΤΕΚΝ.' },
  { lastName: 'ΠΑΠΠΑ', firstName: 'ΙΩΑΝΝΑ', schoolTitle: 'ΕΠΙΧΕΙΡ/ΚΟΥ ΣΧΕΔΙΑΣΜΟΥ & ΠΛΗΡ/ΚΩΝ ΣΥΣΤΗΜΑΤΩΝ ΤΕΙ ΠΑΤΡΑΣ ΚΟΙΝ.ΚΡΙΤ.' },
  { lastName: 'ΠΑΠΠΑΣ', firstName: 'ΚΩΝΣΤΑΝΤΙΝΟΣ', schoolTitle: 'ΓΕΩΠ.ΦΥΤΙΚΗΣ ΠΑΡΑΓ. & ΑΓΡΟΤ. ΠΕΡ/ΝΤΟΣ ΘΕΣΣΑΛΙΑΣ (ΒΟΛΟΣ)' },
  { lastName: 'ΠΑΤΣΟΓΑΣ', firstName: 'ΔΗΜΗΤΡΙΟΣ', schoolTitle: 'ΚΟΙΝΩΝΙΚΗΣ ΠΟΛΙΤΙΚΗΣ ΠΑΝΤΕΙΟΥ ΠΟΛΥΤΕΚΝ.' },
  { lastName: 'ΠΑΤΣΟΓΑΣ', firstName: 'ΘΕΟΔΟΣΙΟΣ', schoolTitle: 'ΧΡΗΜΑΤΟΟΙΚΟΝΟΜΙΚΗΣ & ΕΛΕΓΚΤΙΚΗΣ ΤΕΙ ΗΠΕΙΡΟΥ (ΠΡΕΒΕΖΑ)' },
  { lastName: 'ΠΛΕΥΡΗ', firstName: 'ΟΛΓΑ', schoolTitle: 'ΦΑΡΜΑΚΕΥΤΙΚΗΣ ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΠΛΕΥΡΗΣ', firstName: 'ΓΕΩΡΓΙΟΣ', schoolTitle: 'ΠΟΛΙΤΙΚΩΝ ΜΗΧΑΝΙΚΩΝ ΘΕΣ/ΝΙΚΗΣ ΚΟΙΝ. ΚΡΙΤ.' },
  { lastName: 'ΠΟΥΛΙΑΝΟΥ', firstName: 'ΟΥΡΑΝΙΑ ΧΡΙΣΤ', schoolTitle: 'ΕΠΙΣΤ, ΦΥΣΙΚΗΣ ΑΓΩΓΗΣ & ΑΘΛΗΤΙΣΜΟΥ ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΠΡΙΦΤΙ', firstName: 'ΑΛΕΞΑΝΔΡΑ', schoolTitle: 'ΓΕΩΠΟΝΙΑΣ ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΡΕΝΤΖΟΥ', firstName: 'ΑΝΑΣΤΑΣΙΑ', schoolTitle: 'ΠΛΗΡΟΦΟΡΙΚΗΣ ΙΩΑΝΝΙΝΩΝ ΠΟΛΥΤΕΚΝ.' },
  { lastName: 'ΡΙΖΟΣ', firstName: 'ΜΙΧΑΗΛ', schoolTitle: 'ΝΑΥΤΙΚΩΝ ΔΟΜΙΚΩΝ (Σ.Ν.Δ) ΜΗΧΑΝΙΚΟΙ' },
  { lastName: 'ΡΙΖΟΥ', firstName: 'ΑΝΝΑ', schoolTitle: 'ΜΗΧΑΝΙΚΩΝ ΧΩΡΟΤΑΞΙΑΣ & ΑΝΑΠΤΥΞΗΣ ΘΕΣ/ΝΙΚΗΣ (ΒΕΡΟΙΑ)' },
  { lastName: 'ΡΟΥΜΕΛΙΩΤΗ', firstName: 'ΑΛΕΞΑΝΔΡΑ', schoolTitle: 'ΜΑΘΗΜΑΤΙΚΩΝ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'ΣΑΓΑΝΗΣ', firstName: 'ΓΕΩΡΓΙΟΣ', schoolTitle: 'ΗΛΕΚΤΡΟΛΟΓΙΑΣ ΤΕΙ ΛΑΡΙΣΑ' },
  { lastName: 'ΣΑΚΚΑ', firstName: 'ΚΛΕΟΠΑΤΡΑ', schoolTitle: 'ΛΟΓΙΣΤΙΚΗΣ ΤΕΙ ΗΠΕΙΡΟΥ (ΠΡΕΒΕΖΑ) ΤΡΙΤΕΚΝΟΙ' },
  { lastName: 'ΣΑΛΛΑΣ', firstName: 'ΓΕΩΡΓΙΟΣ', schoolTitle: 'ΟΡΓΑΝΩΣΗΣ & ΔΙΟΙΚΗΣΗΣ ΕΠΙΧΕΙΡΗΣΕΩΝ ΠΕΙΡΑΙΑ ΤΡΙΤΕΚ2011' },
  { lastName: 'ΣΑΡΑΝΤΑΡΗΣ', firstName: 'ΧΡΗΣΤΟΣ', schoolTitle: 'ΓΕΩΠΟΝΙΑΣ ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΣΕΡΒΕΤΑΣ', firstName: 'ΑΔΡΙΑΝΟΣ', schoolTitle: 'ΠΛΑΣΤΙΚΩΝ ΤΕΧΝΩΝ & ΕΠΙΣΤΗΜΩΝ ΤΗΣ ΤΕΧΝΗΣ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'ΣΙΛΙΟΓΚΑ', firstName: 'ΜΑΡΙΑ', schoolTitle: 'ΤΕΧΝΟΛΟΓΙΑΣ ΠΛΗΡΟΦΟΡΙΚΗΣ & ΤΗΛ/ΝΙΩΝ ΤΕΙ ΗΠΕΙΡΟΥ (ΑΡΤΑ)' },
  { lastName: 'ΣΙΝΤΕΛΕΣ', firstName: 'ΑΝΑΣΤΑΣΙΟΣ', schoolTitle: 'ΚΤΗΝΙΑΤΡΙΚΗΣ ΘΕΣΣΑΛΙΑΣ (ΚΑΡΔΙΤΣΑ)' },
  { lastName: 'ΣΙΟΡΕΝΤΑΣ', firstName: 'ΑΓΓΕΛΟΣ', schoolTitle: 'ΗΛΕΚΤΡΟΛΟΓΩΝ ΜΗΧ/ΚΩΝ & ΜΗΧ/ΚΩΝ ΥΠΟΛΟΓΙΣΤΩΝ ΘΡΑΚΗΣ (ΞΑΝΘΗ) ΤΡΙΤΕΚΝΟΙ' },
  { lastName: 'ΣΙΩΖΟΣ', firstName: 'ΛΑΜΠΡΟΣ', schoolTitle: 'ΙΑΤΡΙΚΗΣ ΘΡΑΚΗΣ (ΑΛΕΞΑΝΔΡΟΥΠΟΛΗ) ΤΡΙΤΕΚΝΟΙ' },
  { lastName: 'ΣΚΛΗΒΑΝΙΤΗΣ', firstName: 'ΙΩΑΝΝΗΣ', schoolTitle: 'ΕΠΙΣΤΗΜΩΝ ΠΡΟΣΧΟΛΙΚΗΣ ΑΓΩΓΗΣ & ΕΚΠ/ΣΗΣ ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΣΟΦΟΥΡΗ', firstName: 'ΜΑΡΙΝΑ', schoolTitle: 'ΕΠΙΣΤΗΜΗΣ ΤΩΝ ΥΛΙΚΩΝ ΠΑΤΡΑΣ ΚΟΙΝ, ΚΡΙΤ.' },
  { lastName: 'ΣΤΑΜΟΥΛΗΣ', firstName: 'ΘΕΟΦΙΛΟΣ', schoolTitle: 'ΝΟΣΗΛΕΥΤΙΚΗΣ ΤΕΙ ΗΠΕΙΡΟΥ (ΙΩΑΝΝΙΝΑ)' },
  { lastName: 'ΣΦΡΙΝΤΖΕΡΗΣ', firstName: 'ΣΤΑΥΡΟΣ', schoolTitle: 'ΓΕΩΠΟΝΙΑΣ ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΤΑΤΣΗΣ', firstName: 'ΒΑΣΙΛΕΙΟΣ', schoolTitle: 'ΑΓΡΟΝΟΜΩΝ & ΤΟΠΟΓΡΑΦΩΝ ΜΗΧΑΝΙΚΩΝ ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΤΑΧΟΥ', firstName: 'ΛΟΥΙΖΑ ΕΥΑΓΓΕ', schoolTitle: 'ΠΟΛΙΤΙΚΗΣ ΕΠΙΣΤΗΜΗΣ & ΙΣΤΟΡΙΑΣ ΠΑΝΤΕΙΟΥ' },
  { lastName: 'ΤΡΑΓΟΥΣΤΗ', firstName: 'ΓΕΩΡΓΙΑ', schoolTitle: 'ΕΦΑΡΜΟΣΜΕΝΗΣ ΠΛΗΡΟΦΟΡΙΚΗΣ & ΠΟΛΥΜΕΣΩΝ ΤΕΙ ΚΡΗΤΗΣ (ΗΡΑΚΛΕΙΟ)' },
  { lastName: 'ΤΡΙΑΝΤΑΦΥΛΛΟΥ', firstName: 'ΗΛΙΑΝΑ', schoolTitle: 'ΛΟΓΙΣΤΙΚΗΣ ΤΕΙ ΗΠΕΙΡΟΥ (ΠΡΕΒΕΖΑ)' },
  { lastName: 'ΤΡΟΜΠΟΥΚΗ', firstName: 'ΟΥΡΑΝΙΑ', schoolTitle: 'ΔΙΕΘΝΩΝ & ΕΥΡΩΠ. ΟΙΚΟΝ. ΣΠΟΥΔΩΝ ΟΙΚΟΝΟΜΙΚΟΥ ΠΑΝ. ΑΘΗΝΑΣ' },
  { lastName: 'ΤΡΟΜΠΟΥΚΗΣ', firstName: 'ΧΡΗΣΤΟΣ', schoolTitle: 'ΑΡΧΙΤΕΚΤΟΝΩΝ ΜΗΧΑΝΙΚΩΝ ΘΡΑΚΗΣ (ΞΑΝΘΗ) ΠΟΛΥΤ2011' },
  { lastName: 'ΤΣΕΒΡΕΝΙΖΟΥ', firstName: 'ΙΟΛΗ', schoolTitle: 'ΠΛΗΡΟΦΟΡΙΚΗΣ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'ΤΣΙΑΜΠΑΣ', firstName: 'ΟΡΕΣΤΗΣ', schoolTitle: 'ΠΟΛΙΤΙΚΩΝ ΜΗΧΑΝΙΚΩΝ ΠΑΤΡΑΣ' },
  { lastName: 'ΤΣΙΡΩΝΗΣ', firstName: 'ΛΕΩΝΙΔΑΣ', schoolTitle: 'ΠΟΛΙΤΙΚΩΝ ΜΗΧΑΝΙΚΩΝ ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΤΣΟΥΦΗ', firstName: 'ΑΦΡΟΔΙΤΗ', schoolTitle: 'ΦΥΣΙΚΗΣ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'ΤΣΟΦΥΛΛΑΣ', firstName: 'ΠΕΤΡΟΣ', schoolTitle: 'ΙΣΤΟΡΙΑΣ & ΑΡΧΑΙΟΛΟΓΙΑΣ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'ΤΥΡΟΛΟΓΟΣ', firstName: 'ΑΛΕΞΙΟΣ', schoolTitle: 'ΜΗΧΑΝΟΛΟΓΩΝ ΜΗΧΑΝΙΚΩΝ ΔΥΤ. ΜΑΚΕΔΟΝΙΑΣ (ΚΟΖΑΝΗ) ΠΟΛΥΤ 2011' },
  { lastName: 'ΦΑΚΟΥ', firstName: 'ΜΑΡΙΚΑ', schoolTitle: 'ΔΗΜΟΣΙΟΓΡΑΦΙΑΣ & ΜΕΣΩΝ ΜΑΖΙΚΗΣ ΕΠΙΚΟΙΝΩΝΙΑΣ ΘΕΣ/ΝΙΚΗΣ ΚΟΙΝ. ΚΡΙΤ.' },
  { lastName: 'ΦΕΛΕΚΗΣ', firstName: 'ΧΡΗΣΤΟΣ', schoolTitle: 'ΖΩΙΚΗΣ ΠΑΡΑΓΩΓΗΣ ΤΕΙ ΗΠΕΙΡΟΥ (ΑΡΤΑ)' },
  { lastName: 'ΦΡΑΓΚΑΤΣΗ', firstName: 'ΘΕΟΔΩΡΑ', schoolTitle: 'ΟΙΚΟΝΟΜΙΚΩΝ ΕΠΙΣΤΗΜΩΝ ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΦΡΑΓΚΑΤΣΗ', firstName: 'ΦΩΤΕΙΝΗ', schoolTitle: 'ΟΡΓΑΝΩΣΗΣ & ΔΙΟΙΚΗΣΗΣ ΕΠΙΧΕΙΡΗΣΕΩΝ ΜΑΚΕΔΟΝΙΑΣ (ΘΕΣ/ΝΙΚΗ)' },
  { lastName: 'ΦΩΤΑΚΗ', firstName: 'ΒΑΣΙΛΙΚΗ', schoolTitle: 'ΦΥΣΙΚΗΣ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'ΦΩΤΙΑΔΗΣ', firstName: 'ΑΧΙΛΛΕΑΣ', schoolTitle: 'ΟΙΚΟΝΟΜΙΚΩΝ ΕΠΙΣΤΗΜΩΝ ΜΑΚΕΔΟΝΙΑΣ (ΘΕΣ/ΝΙΚΗΣ)' },
  { lastName: 'ΧΑΡΑΛΑΜΠΟΥΣ', firstName: 'ΒΑΣΙΛΕΙΟΣ', schoolTitle: 'ΗΛΕΚΤΡΟΛΟΓΙΑΣ ΤΕΙ ΛΑΜΙΑΣ' },
  { lastName: 'ΧΡΗΣΤΟΥ', firstName: 'ΕΛΠΙΔΑ', schoolTitle: 'ΑΡΧΙΤΕΚΤΟΝΙΚΗΣ ΤΟΠΙΟΥ ΤΕΙ ΚΑΒΑΛΑΣ (ΔΡΑΜΑ)' },
  { lastName: 'ΧΡΗΣΤΟΥ', firstName: 'ΜΑΓΔΑ', schoolTitle: 'ΑΡΧΕΙΟΝΟΜΙΑΣ & ΒΙΒΛΙΟΘΗΚΟΝΟΜΙΑΣ ΙΟΝΙΟΥ (ΚΕΡΚΥΡΑ)' },
  { lastName: 'ΨΩΜΑ', firstName: 'ΟΥΡΑΝΙΑ', schoolTitle: 'ΙΑΤΡΙΚΗΣ ΙΩΑΝΝΙΝΩΝ' },
];

export const students2013: Student[] = [
  { lastName: 'ΒΑΔΙΒΟΥΛΗΣ', firstName: 'ΘΕΟΧΑΡΗΣ', schoolTitle: 'ΓΕΩΠΟΝΙΑΣ ΒΟΛΟΥ' },
  { lastName: 'ΒΑΡΕΛΗΣ', firstName: 'ΒΑΣΙΛΕΙΟΣ', schoolTitle: 'ΜΗΧΑΝΙΚΩΝ ΗΛΕΚΤΡ. ΥΠΟΛ. ΠΑΤΡΑ' },
  { lastName: 'ΒΑΣΙΛΑΚΗ', firstName: 'ΑΓΓΕΛΙΚΗ', schoolTitle: 'ΜΗΧΑΝΟΛΟΓΩΝ ΜΗΧ. ΤΕ ΛΑΡΙΣΑ' },
  { lastName: 'ΒΑΣΙΛΕΙΑΔΗΣ', firstName: 'ΑΝΑΣΤΑΣΙΟΣ', schoolTitle: 'ΜΗΧΑΝ. ΗΛΕΚΤΡ. ΥΠΟΛ. ΠΑΤΡΑ' },
  { lastName: 'ΒΑΣΙΛΕΙΟΥ', firstName: 'ΑΓΓΕΛΟΣ', schoolTitle: 'ΠΟΛΙΤΙΚΩΝ ΜΗΧ. ΤΕ ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΒΕΛΙΟΣ', firstName: 'ΝΙΚΟΛΑΟΣ', schoolTitle: 'ΙΑΤΡΙΚΗ ΙΩΑΝΝΙΝΑ' },
  { lastName: 'ΒΛΑΧΟΥ', firstName: 'ΧΡΥΣΟΥΛΑ', schoolTitle: 'ΦΥΣΙΚΟΘΕΡΑΠΕΙΑΣ ΘΕΣ/ΝΙΚΗ' },
  { lastName: 'ΓΑΛΗΝΑΣ', firstName: 'ΚΩΝ/ΝΟΣ', schoolTitle: 'ΤΕΧΝΟΛΟΓΙΑΣ ΤΡΟΦΙΜΩΝ ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΓΕΜΟΣ', firstName: 'ΑΘΑΝΑΣΙΟΣ', schoolTitle: 'ΠΛΗΡΟΦΟΡΙΚΗΣ ΚΕΡΚΥΡΑ' },
  { lastName: 'ΓΕΡΟΔΗΜΟΣ', firstName: 'ΕΥΑΓΓΕΛΟΣ', schoolTitle: 'ΗΛΕΚΤΡ. ΜΗΧ. ΤΕ ΛΑΜΙΑ' },
  { lastName: 'ΓΕΩΡΓΑΚΗΣ', firstName: 'ΝΙΚΟΛΑΟΣ', schoolTitle: 'ΠΟΛΙΤΙΚΟΣ ΜΗΧ. ΠΑΤΡΑ' },
  { lastName: 'ΓΕΩΡΓΑΚΟΠΟΥΛΟΥ', firstName: 'ΦΩΤΕΙΝΗ', schoolTitle: 'ΑΡΧΙΤΕΚΤΟΝΩΝ. ΜΗΧΑΝ. ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΓΕΩΡΓΙΟΥ', firstName: 'ΧΡΙΣΤΙΝΑ', schoolTitle: 'ΟΙΚΟΝΟΜΙΚΩΝ ΕΠΙΣΤΗΜΩΝ ΙΩΑΝΝΙΝΑ' },
  { lastName: 'ΓΚΑΒΑΡΔΙΝΑΣ', firstName: 'ΟΘΩΝ', schoolTitle: 'ΜΗΧ.ΟΡΥΚΤΩΝ ΠΟΡΩΝ ΧΑΝΙΑ' },
  { lastName: 'ΓΚΑΝΑΡΑ', firstName: 'ΔΗΜΗΤΡΑ', schoolTitle: 'ΜΗΧ. ΕΠΙΣΤΗΜ. ΥΛΙΚΩΝ ΙΩΑΝΝΙΝΑ' },
  { lastName: 'ΓΚΑΡΤΖΟΝΙΚΑ', firstName: 'ΙΩΑΝΝΑ', schoolTitle: 'ΗΛΕΚΤΡ. ΜΗΧ. & ΜΗΧ. ΥΠΟΛ. ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΓΚΑΡΤΖΩΝΗ', firstName: 'ΚΥΡΙΑΚΗ', schoolTitle: 'ΠΟΛΙΤΙΚΩΝ ΜΗΧ. ΤΕ ΤΡΙΚΑΛΑ' },
  { lastName: 'ΓΡΕΒΕΝΙΩΤΗ', firstName: 'ΙΩΑΝΝΑ', schoolTitle: 'ΟΙΚΟΝΟΜΙΚΩΝ ΕΠΙΣΤΗΜΩΝ ΙΩΑΝΝΙΝΑ' },
  { lastName: 'ΔΗΜΗΤΡΙΟΥ', firstName: 'ΒΛΑΣΙΟΣ', schoolTitle: 'ΟΙΚΟΝΟΜΙΚΩΝ ΕΠΙΣΤΗΜΩΝ ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΔΗΜΗΤΡΙΟΥ', firstName: 'ΘΕΟΔΩΡΑ', schoolTitle: 'ΧΗΜΙΚΩΝ ΜΗΧ. ΑΘΗΝΑ' },
  { lastName: 'ΔΡΑΚΟΣ', firstName: 'ΝΙΚΟΛΑΟΣ', schoolTitle: 'ΑΣΤΥΦΥΛΑΚΩΝ' },
  { lastName: 'ΕΡΗΜΟΥ', firstName: 'ΑΣΗΜΙΝΑ', schoolTitle: 'ΟΡΓΑΝ. & ΔΙΟΙΚ. ΑΘΛΗΤΙΣΜΟΥ ΣΠΑΡΤΗ' },
  { lastName: 'ΖΙΩΓΑ', firstName: 'ΕΛΕΝΗ', schoolTitle: 'ΗΛΕΚΤΡ. ΜΗΧ. & ΜΗΧ. ΥΠΟΛΟΓΙΣΤΩΝ ΑΘΗΝΑ' },
  { lastName: 'ΚΑΛΑΜΠΟΚΗΣ', firstName: 'ΛΑΜΠΡΟΣ', schoolTitle: 'ΒΙΟΜΗΧ. ΣΧΕΔΙΑΣΜΟΥ ΤΕ ΚΟΖΑΝΗ' },
  { lastName: 'ΚΑΠΟΔΙΣΤΡΙΑ', firstName: 'ΦΩΤΕΙΝΗ', schoolTitle: 'ΠΑΙΔΑΓΩΙΚΟ ΡΕΘΥΜΝΟΥ' },
  { lastName: 'ΚΑΣΣΕΛΟΥΡΗΣ', firstName: 'ΑΝΑΣΤΑΣΙΟΣ', schoolTitle: 'ΟΡΓΑΝ. & ΔΙΟΙΚ. ΕΠΙΧ.ΘΕΣ/ΝΙΚΗ' },
  { lastName: 'ΚΑΤΕΡΟΣ', firstName: 'ΚΩΝ/ΝΟΣ', schoolTitle: 'ΗΛΕΚΤΡ. ΜΗΧ & ΜΗΧ. ΥΠΟΛ. ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΚΛΑΦΟΥΝΗΣ', firstName: 'ΑΡΙΣΤΕΙΔΗΣ', schoolTitle: 'ΔΑΣΟΛΟΠΑΣ ΘΕΣ/ΝΙΚΗ' },
  { lastName: 'ΚΟΛΙΟΣ', firstName: 'ΒΑΣΙΛΕΙΟΣ', schoolTitle: 'ΙΚΑΡΩΝ ΜΗΧΑΝ. ΣΜΑ' },
  { lastName: 'ΚΟΛΙΟΥ', firstName: 'ΠΑΡΑΣΚΕΥΗ', schoolTitle: 'ΕΦΑΡΜ.ΜΑΘΗΜΑΤΙΚΩΝ ΑΘΗΝΑ' },
  { lastName: 'ΚΟΛΙΟΥΛΗΣ', firstName: 'ΒΑΣΙΛΕΙΟΣ', schoolTitle: 'ΟΡΓΑΝ. & ΔΙΟΙΚ. ΑΘΛΗΤΙΣΜΟΥ ΣΠΑΡΤΗ' },
  { lastName: 'ΚΟΛΤΟΥΚΗ', firstName: 'ΒΑΣΙΛΙΚΗ', schoolTitle: 'ΒΙΟΛΟΓΙΚΩΝ ΕΦΑΡΜ. & ΤΕΧΝΟΛ. ΙΩΑΝΝΙΝΑ' },
  { lastName: 'ΚΟΥΤΣΟΣ', firstName: 'ΚΩΝ/ΝΟΣ', schoolTitle: 'ΔΙΟΙΚ ΕΠΙΧΕΙΡΗΣΕΩΝ ΠΑΤΡΑ' },
  { lastName: 'ΚΥΡΟΥ', firstName: 'ΑΛΙΚΗ', schoolTitle: 'ΠΟΛΙΤΙΚΩΝ ΜΗΧ. ΠΑΤΡΑ' },
  { lastName: 'ΚΩΣΤΟΥΛΑ', firstName: 'ΠΑΡΑΣΚΕΥΗ', schoolTitle: 'ΣΜΥΝ' },
  { lastName: 'ΚΩΣΤΟΥΛΑΣ', firstName: 'ΧΡΗΣΤΟΣ', schoolTitle: 'ΓΕΩΠΟΝΙΑ ΑΘΗΝΑΣ' },
  { lastName: 'ΚΩΤΣΙΟΥΡΟΥ', firstName: 'ΒΑΡΒΑΡΑ', schoolTitle: 'ΦΥΣΙΚΗΣ ΑΘΗΝΑ' },
  { lastName: 'ΛΕΚΟΣ', firstName: 'ΔΗΜΗΤΡΙΟΣ', schoolTitle: 'ΓΕΩΠΟΝΙΑΣ ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΛΕΚΟΥ', firstName: 'ΧΑΡΙΤΙΝΗ', schoolTitle: 'ΧΗΜΕΙΑΣ ΘΕΣ/ΝΙΚΗ' },
  { lastName: 'ΛΟΥΤΣΑΡΗ', firstName: 'ΕΛΕΝΗ', schoolTitle: 'ΠΟΛΙΤΙΚΩΝ ΜΗΧ.ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΜΑΛΛΙΟΣ', firstName: 'ΤΑΞΙΑΡΧΗΣ', schoolTitle: 'ΣΧΟΛΗ ΠΛΟΙΑΡΧΩΝ Ε.Ν.' },
  { lastName: 'ΜΑΝΙΦΑΒΑΣ', firstName: 'ΓΕΩΡΓΙΟΣ', schoolTitle: 'ΑΣΤΥΦΥΛΑΚΩΝ' },
  { lastName: 'ΜΑΝΙΦΑΒΑΣ', firstName: 'ΣΩΚΡΑΤΗΣ', schoolTitle: 'ΓΕΩΠΟΝΙΑΣ ΒΟΛΟΥ' },
  { lastName: 'ΜΑΝΟΣ', firstName: 'ΠΕΤΡΟΣ', schoolTitle: 'ΣΧΟΛΗ ΜΗΧ. ΕΜΠΟΡ. ΝΑΥΤΙΚΟΥ' },
  { lastName: 'ΜΑΡΟΣ', firstName: 'ΑΛΕΞ/ΔΡΟΣ', schoolTitle: 'ΔΙΟΙΚΗΣΗ ΕΠΙΧΕΙΡΗΣΕΩΝ ΧΙΟΣ' },
  { lastName: 'ΜΗΛΙΩΝΗ', firstName: 'ΜΑΡΙΑΛΕΝΑ', schoolTitle: 'ΠΟΛΙΤΙΚΩΝ ΜΗΧΑΝΙΚΩΝ ΠΑΤΡΑΣ' },
  { lastName: 'ΜΠΑΛΑΦΑ', firstName: 'ΕΛΕΝΗ', schoolTitle: 'ΜΗΧΑΝ. ΠΛΗΡ/ΚΗΣ ΤΕ ΑΡΤΑ' },
  { lastName: 'ΜΠΕΣΛΙΚΑ', firstName: 'ΜΑΡΙΝΑ', schoolTitle: 'ΠΟΛΙΤΙΚΩΝ ΜΗΧ. ΤΕ ΛΑΡΙΣΑ' },
  { lastName: 'ΜΠΟΒΟΛΟΥ', firstName: 'ΕΥΦΡΟΣΥΝΗ', schoolTitle: 'ΑΓΡΟΤΙΚΗΣ ΑΝΑΠΤΥΞΗΣ ΟΡΕΣΤΙΑΔΑ' },
  { lastName: 'ΜΠΟΥΓΙΑΣ', firstName: 'ΧΡΗΣΤΟΣ', schoolTitle: 'ΜΑΘΗΜΑΤΙΚΩΝ ΠΑΤΡΑΣ' },
  { lastName: 'ΜΠΟΥΡΑΝΤΑΣ', firstName: 'ΕΥΑΓΓΕΛΟΣ', schoolTitle: 'ΦΥΣΙΚΗΣ ΙΩΑΝΝΙΝΑ' },
  { lastName: 'ΜΠΟΥΡΗ', firstName: 'ΚΩΝ/ΝΑ', schoolTitle: 'ΕΠΙΣΤΗΜΗΣ ΦΥΣ. ΑΓΩΓΗΣΑ ΑΘΛ. ΘΕΣ/ΝΙΚΗ' },
  { lastName: 'ΜΠΡΑΝΙΚΑΣ', firstName: 'ΕΥΣΤΑΘΙΟΣ', schoolTitle: 'ΗΛΕΚΤΡ. ΜΗΧ. & ΤΕΧΝΟΛΟΓΙΑΣ ΥΠΟΛ. ΠΑΤΡΑ' },
  { lastName: 'ΜΟΛΩΝΗΣ', firstName: 'ΕΥΑΓΓΕΛΟΣ', schoolTitle: 'ΜΗΧ. ΠΕΤΡΕΛ. ΚΑΒΑΛΑΣ' },
  { lastName: 'ΝΑΚΑΣ', firstName: 'ΚΩΝ/ΝΟΣ', schoolTitle: 'ΙΑΤΡΙΚΗ ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΝΑΚΟΣ', firstName: 'ΕΥΣΤΑΘΙΟΣ', schoolTitle: 'ΗΛΕΚΤΡ. ΜΗΧ. ΤΕ ΚΑΒΑΛΑ' },
  { lastName: 'ΝΑΚΟΥ', firstName: 'ΑΛΕΞΑΝΔΡΑ', schoolTitle: 'ΜΗΧ. ΠΛΗΡ/ΚΗΣ ΑΘΗΝΑ' },
  { lastName: 'ΝΙΚΟΛΑΟΥ', firstName: 'ΑΙΚΑΤΕΡΙΝΗ', schoolTitle: 'ΙΑΤΡΙΚΗΣ ΙΩΑΝΝΙΝΑ' },
  { lastName: 'ΝΙΚΟΛΑΟΥ', firstName: 'ΔΗΜΗΤΡΙΟΣ', schoolTitle: 'ΔΙΑΧ. ΠΕΡΙΒ. & ΦΥΣΙΚΩΝ ΠΟΡΩΝ ΑΓΡΙΝΙΟ' },
  { lastName: 'ΝΤΑΛΑΟΥΤΗΣ', firstName: 'ΑΝΔΡΕΑΣ', schoolTitle: 'ΙΑΤΡΙΚΗ ΑΘΗΝΑΣ' },
  { lastName: 'ΟΙΚΟΝΟΜΙΔΗΣ', firstName: 'ΙΩΑΝΝΗΣ', schoolTitle: 'ΧΗΜΙΚΩΝ ΜΗΧ.ΠΑΤΡΑ' },
  { lastName: 'ΠΑΠΑΚΩΣΤΑΣ', firstName: 'ΙΩΑΝΝΗΣ', schoolTitle: 'ΧΗΜΕΙΑΣ ΙΩΑΝΝΙΝΑ' },
  { lastName: 'ΠΑΠΑΝΙΚΟΛΑΟΥ', firstName: 'ΚΩΝ/ΝΟΣ', schoolTitle: 'ΟΙΚΟΝΟΜΙΚΩΝ ΕΠΙΣΤΗΜΩΝ ΑΘΗΝΑ' },
  { lastName: 'ΠΑΠΑΡΟΥΝΗ', firstName: 'ΘΕΟΔΩΡΑ', schoolTitle: 'ΗΛΕΚΤΡ. ΜΗΧ. & ΜΗΧ. ΥΠΟΛΟΓΙΣΤΩΝ ΑΘΗΝΑ' },
  { lastName: 'ΠΑΠΑΧΡΗΣΤΟΣ', firstName: 'ΕΥΑΓΓΕΛΟΣ', schoolTitle: 'ΜΗΧΑΝΙΚΩΝ ΠΛΗΡ. ΚΟΖΑΝΗΣ' },
  { lastName: 'ΠΑΠΠΑ', firstName: 'ΑΡΤΕΜΙΣ', schoolTitle: 'ΛΟΓΙΣΤΙΚΗΣ & ΧΡΗΜ/ΟΙΚΟΝΟΜΙΚΗΣ ΘΕΣ/ΝΙΚΗ' },
  { lastName: 'ΠΑΠΠΑ', firstName: 'ΕΥΘΑΛΙΑ', schoolTitle: 'ΛΟΓΙΣΤΙΚΗΣ & ΧΡΗΜ/ΟΙΚΟΝΟΜΙΚΗΣ ΑΘΗΝΑ' },
  { lastName: 'ΠΑΠΠΑΣ', firstName: 'ΚΩΝ/ΝΟΣ', schoolTitle: 'ΔΙΟΙΚΗΣΗ ΕΠΙΧ. ΓΡΕΒΕΝΑ' },
  { lastName: 'ΠΑΤΣΟΓΑΣ', firstName: 'ΘΕΟΔΟΣΙΟΣ', schoolTitle: 'ΑΣΤΥΦΥΛΑΚΩΝ' },
  { lastName: 'ΠΑΧΗΣ', firstName: 'ΧΡΗΣΤΟΣ', schoolTitle: 'ΜΗΧΑΝΟΛΟΓΩΝ ΜΗΧ. ΚΟΖΑΝΗΣ' },
  { lastName: 'ΡΑΠΤΗ', firstName: 'ΠΑΡΑΣΚΕΥΗ', schoolTitle: 'ΔΙΟΙΚΗΣΗ ΕΠΙΧΕΙΡΗΣΕΩΝ ΑΓΡΙΝΙΟ' },
  { lastName: 'ΣΑΛΛΑΣ', firstName: 'ΓΕΩΡΓΙΟΣ', schoolTitle: 'ΟΡΓΑΝΩΣΗ & ΔΙΟΙΚΗΣΗ ΕΠΙΧ. ΠΕΙΡΑΙΑ' },
  { lastName: 'ΣΙΛΙΟΓΚΑ', firstName: 'ΒΑΠΑ', schoolTitle: 'ΠΟΛΙΤΙΚΩΝ ΜΗΧ. ΑΘΗΝΑ' },
  { lastName: 'ΣΠΥΡΟΥ', firstName: 'ΛΑΜΠΡΟΣ', schoolTitle: 'ΤΕΧΝΟΛΟΓΩΝ ΓΕΩΠΟΝΩΝ ΑΜΑΛΙΑΔΑ' },
  { lastName: 'ΤΖΑΛΟΚΩΣΤΑ', firstName: 'ΕΛΕΝΗ', schoolTitle: 'ΟΙΚΟΝΟΜΙΚΩΝ ΕΠΙΣΤΗΜΩΝ ΙΩΑΝΝΙΝΑ' },
  { lastName: 'ΤΖΩΡΑ', firstName: 'ΠΑΝΑΠΩΤΑ', schoolTitle: 'ΠΛΗΡΟΦΟΡΙΚΗΣ ΤΕ ΑΡΤΑ' },
  { lastName: 'ΤΡΙΜΠΟΥ', firstName: 'ΑΓΓΕΛΙΚΗ', schoolTitle: 'ΜΗΧΑΝΙΚΩΝ ΠΕΤΡΕΛΑΙΟΥ ΚΑΒΑΛΑ' },
  { lastName: 'ΤΣΑΜΗ', firstName: 'ΑΙΚΑΤΕΡΙΝΗ', schoolTitle: 'ΟΡΓΑΝΩΣΗ & ΔΙΟΙΚ. ΕΠΙΧ. ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΦΕΛΕΚΗΣ', firstName: 'ΧΡΗΣΤΟΣ', schoolTitle: 'ΔΙΑΧ. ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΑΓΡΙΝΙΟ' },
  { lastName: 'ΦΩΤΗ', firstName: 'ΑΙΚΑΤΕΡΙΝΗ', schoolTitle: 'ΑΣΠΑΙΤΕ' },
  { lastName: 'ΧΑΛΚΙΑΣ', firstName: 'ΗΛΙΑΣ', schoolTitle: 'ΟΡΓΑΝΩΣΗ & ΔΙΟΙΚ. ΕΠΙΧ. ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΧΑΡΑΛΑΜΠΟΥΣ', firstName: 'ΒΑΣΙΛΕΙΟΣ', schoolTitle: 'ΣΧΟΛΗ ΜΗΧΑΝΙΚΩΝ ΕΜΠΟΡΙΚΟΥ ΝΑΥΤΙΚΟΥ' },
  { lastName: 'ΒΑΪΤΣΗΣ', firstName: 'ΑΠΟΣΤΟΛΟΣ', schoolTitle: 'ΙΑΤΡΙΚΗ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'ΤΣΙΜΠΕΡΗ', firstName: 'ΑΡΤΕΜΙΣ', schoolTitle: 'ΦΥΣΙΚΟ ΘΕΣΣΑΛΟΝΙΚΗΣ' },
];

export const students2014: Student[] = [
  { lastName: 'ΑΝΑΣΤΑΣΟΠΟΥΛΟΥ', firstName: 'ΑΝΑΣΤΑΣΙΑ', schoolTitle: 'ΟΙΚΟΝΟΜΙΚΗΣ ΕΠΙΣΤΗΜΗΣ ΑΘΗΝΑΣ' },
  { lastName: 'ΑΝΤΩΝΙΟΥ', firstName: 'ΒΑΣΙΛΙΚΗ', schoolTitle: 'ΦΥΣΙΚΗΣ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'ΑΡΚΟΥΜΑΝΗ', firstName: 'ΓΕΩΡΓΙΑ', schoolTitle: 'ΠΛΗΡΟΦΟΡΙΚΗΣ ΑΘΗΝΑΣ' },
  { lastName: 'ΑΥΓΕΡΗΣ', firstName: 'ΒΑΣΙΛΕΙΟΣ', schoolTitle: 'ΗΛΕΚΤΡΟΛΟΓΩΝ ΜΗΧΑΝΙΚΩΝ Τ.Ε. ΛΑΡΙΣΑΣ' },
  { lastName: 'ΓΚΑΡΤΖΟΝΙΚΑ', firstName: 'ΚΑΛΛΙΟΠΗ', schoolTitle: 'ΔΙΟΙΚΗΣΗΣ ΕΠΙΧΕΙΡΗΣΕΩΝ ΜΕΣΟΛΟΓΓΙΟΥ' },
  { lastName: 'ΓΚΟΥΝΤΑ', firstName: 'ΘΕΟΔΩΡΑ ΜΑΡΙΑ', schoolTitle: 'ΟΙΚΟΝΟΜΙΚΩΝ ΕΠΙΣΤΗΜΩΝ ΤΡΙΠΟΛΗΣ' },
  { lastName: 'ΓΟΥΣΙΑ', firstName: 'ΕΛΕΝΗ', schoolTitle: 'ΛΟΓΙΣΤΙΚΗΣ ΚΑΙ ΧΡΗΜΑΤΟΟΙΚΟΝΟΜΙΚΗΣ ΑΘΗΝΑΣ' },
  { lastName: 'ΔΕΛΗΚΟΥΡΑΣ', firstName: 'ΣΠΥΡΙΔΩΝ', schoolTitle: 'ΤΕΧΝΟΛΟΓΩΝ ΓΕΩΠΟΝΩΝ ΑΡΤΑΣ' },
  { lastName: 'ΔΗΜΟΥ', firstName: 'ΔΗΜΗΤΡΑ', schoolTitle: 'ΟΙΚΟΝΟΜΙΚΩΝ ΕΠΙΣΤΗΜΩΝ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'ΔΡΑΚΟΥ', firstName: 'ΑΝΝΑ ΜΑΡΙΑ', schoolTitle: 'ΧΗΜΕΙΑΣ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'ΖΙΩΡΗΣ', firstName: 'ΓΕΩΡΓΙΟΣ', schoolTitle: 'ΙΑΤΡΙΚΗΣ ΑΛΕΞΑΝΔΡΟΥΠΟΛΗΣ' },
  { lastName: 'ΖΩΤΟΣ', firstName: 'ΓΡΗΓΟΡΙΟΣ', schoolTitle: 'ΔΙΑΧ. ΠΕΡ/ΝΤΟΣ & ΦΥΣΙΚΩΝ ΠΟΡΩΝ ΑΓΡΙΝΙΟΥ' },
  { lastName: 'ΘΑΝΑΣΗΣ', firstName: 'ΚΩΝ/ΝΟΣ', schoolTitle: 'ΜΗΧ/ΚΩΝ ΠΛΗΡ/ΚΗΣ & ΤΗΛ/ΝΙΩΝ ΚΟΖΑΝΗΣ' },
  { lastName: 'ΚΕΦΑΛΑ', firstName: 'ΚΛΕΙΩ', schoolTitle: 'ΙΣΤΟΡΙΑΣ & ΑΡΧΑΙΟΛΟΓΙΑΣ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'ΚΑΛΛΙΑ ΣΠΕΝΤΖΑ', firstName: 'ΑΓΓΕΛΙΚΗ', schoolTitle: 'ΒΙΟΛΟΓΙΑΣ ΗΡΑΚΛΕΙΟΥ' },
  { lastName: 'ΚΑΡΑΓΕΩΡΓΟΥ', firstName: 'ΠΑΝΑΓΙΩΤΑ', schoolTitle: 'ΝΟΣΗΛΕΥΤΙΚΗΣ ΑΘΗΝΑΣ' },
  { lastName: 'ΚΑΡΑΓΙΑΝΝΗΣ', firstName: 'ΓΕΩΡΓΙΟΣ', schoolTitle: 'ΤΟΠΟΓΡΑΦΩΝ-ΑΓΡΟΝΟΜΩΝ-ΜΗΧΑΝΙΚΩΝ ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΚΑΡΑΓΙΑΝΝΗΣ', firstName: 'ΔΗΜΗΤΡΙΟΣ', schoolTitle: 'ΜΑΘΗΜΑΤΙΚΩΝ ΘΕΣΣΑΛΟΝΙΚΗΣ' },
  { lastName: 'ΚΑΡΑΓΙΩΡΓΟΣ', firstName: 'ΑΘΑΝΑΣΙΟΣ', schoolTitle: 'ΟΙΚΟΝΟΜΙΚΟ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'ΚΟΓΙΑΝΤΗ', firstName: 'ΚΩΝ/ΝΑ ΜΑΡΙΑ', schoolTitle: 'ΜΟΝΙΜΩΝ ΥΠΑΞΙΩΜΑΤΙΚΩΝ ΣΤΡΑΤΟΥ (ΣΜΥ)' },
  { lastName: 'ΚΟΛΙΟΣ', firstName: 'ΒΑΣΙΛΕΙΟΣ', schoolTitle: 'ΗΛΕΚΤΡ. ΜΗΧ. & ΜΗΧ. ΥΠΟΛΟΓΙΣΤΩΝ ΑΘΗΝΑΣ' },
  { lastName: 'ΚΟΜΑΤΣΟΥΛΗΣ', firstName: 'ΧΡΗΣΤΟΣ', schoolTitle: 'ΜΗΧΑΝΙΚΩΝ ΠΛΗΡΟΦΟΡΙΚΗΣ Τ.Ε. ΑΡΤΑΣ' },
  { lastName: 'ΚΟΣΣΥΒΑΚΗΣ', firstName: 'ΕΥΡΙΠΙΔΗΣ', schoolTitle: 'ΜΗΧ/ΚΩΝ ΜΕΤΑΛΛΕΙΩΝ ΜΕΤ/ΡΓΩΝ ΑΘΗΝΑΣ' },
  { lastName: 'ΚΟΤΣΙΛΛΟΣ', firstName: 'ΛΕΩΝΙΔΑΣ', schoolTitle: 'ΙΣΤ. ΑΡΧ. & ΔΙΑΧ. ΠΟΛΙΤΙΣΤΙΚΩΝ ΑΓΑΘΩΝ ΚΑΛΑΜΑΤΑΣ' },
  { lastName: 'ΚΟΥΣΟΥΛΑΣ', firstName: 'ΓΕΩΡΓΙΟΣ', schoolTitle: 'ΜΗΧΑΝΙΚΩΝ ΠΛΗΡΟΦΟΡΙΚΗΣ Τ.Ε. ΑΡΤΑΣ' },
  { lastName: 'ΚΩΣΤΑΣ', firstName: 'ΘΕΟΦΑΝΗΣ', schoolTitle: 'ΜΗΧΑΝΟΛΟΓΩΝ ΜΗΧΑΝΙΚΩΝ ΚΟΖΑΝΗΣ' },
  { lastName: 'ΛΑΜΠΡΗ', firstName: 'ΒΑΓΙΑ', schoolTitle: 'ΜΑΘΗΜΑΤΙΚΩΝ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'ΜΑΝΙΦΑΒΑΣ', firstName: 'ΣΩΚΡΑΤΗΣ', schoolTitle: 'ΕΠΙΣΤ. ΖΩΙΚΗΣ ΠΑΡΑΓΩΓΗΣ & ΥΔΑΤΙΩΝ ΑΘΗΝΑΣ' },
  { lastName: 'ΜΑΝΟΥ', firstName: 'ΑΓΝΗ', schoolTitle: 'ΧΡΗΜ/ΚΗΣ & ΤΡΑΠΕΖΙΚΗΣ ΔΙΟΙΚ. ΠΕΙΡΑΙΑ' },
  { lastName: 'ΜΑΡΓΩΝΗ', firstName: 'ΑΡΤΕΜΙΣ', schoolTitle: 'ΕΦΑΡΜΟΣΜΕΝΩΝ ΜΑΘ/ΚΩΝ & ΦΥΣ. ΕΠΙΣΤΗΜΩΝ ΑΘΗΝΑΣ' },
  { lastName: 'ΜΑΡΓΩΝΗ', firstName: 'ΣΟΦΙΑ', schoolTitle: 'ΟΠΥ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'ΜΑΡΟΣ', firstName: 'ΑΛΕΞΑΝΔΡΟΣ', schoolTitle: 'ΟΙΚΟΝΟΜΙΚΩΝ ΕΠΙΣΤΗΜΩΝ ΡΕΘΥΜΝΟΥ' },
  { lastName: 'ΜΙΧΑΛΗ', firstName: 'ΧΡΥΣΑΝΘΗ', schoolTitle: 'ΞΕΝΩΝ ΓΛ. ΜΕΤΑΦΡΑΣΗΣ & ΔΙΕΡΜΗΝΕΙΑΣ ΚΕΡΚΥΡΑΣ' },
  { lastName: 'ΜΙΧΑΛΗ', firstName: 'ΗΛΙΑΝΑ', schoolTitle: 'ΤΕΧΝΩΝ ΗΧΟΥ ΚΑΙ ΕΙΚΟΝΑΣ ΚΕΡΚΥΡΑΣ' },
  { lastName: 'ΜΠΑΛΑΦΑ', firstName: 'ΕΛΕΝΗ', schoolTitle: 'ΟΙΚΟΝΟΜΙΚΩΝ ΕΠΙΣΤΗΜΩΝ ΑΘΗΝΑΣ' },
  { lastName: 'ΜΠΑΛΑΦΑΣ', firstName: 'ΠΑΝΑΓΙΩΤΗΣ', schoolTitle: 'ΣΧΟΛΗ ΠΛΟΙΑΡΧΩΝ' },
  { lastName: 'ΜΠΟΥΚΑΣ', firstName: 'ΚΩΝ/ΝΟΣ', schoolTitle: 'ΜΗΧ. ΧΩΡΟΤΑΞΙΑΣ & ΑΝΑΠΤΥΞΗΣ ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΜΠΟΥΡΑΝΤΑΣ', firstName: 'ΕΥΑΓΓΕΛΟΣ', schoolTitle: 'ΙΚΑΡΩΝ (ΣΙ) ΙΠΤΑΜΕΝΟΙ' },
  { lastName: 'ΜΠΟΥΡΓΑΝΗ', firstName: 'ΜΑΡΙΑ', schoolTitle: 'ΙΑΤΡΙΚΗ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'NAKA', firstName: 'ΑΝΘΗ', schoolTitle: 'ΙΑΤΡΙΚΩΝ ΕΡΓΑΣΤΗΡΙΩΝ ΛΑΡΙΣΑΣ' },
  { lastName: 'ΝΑΚΟΣ', firstName: 'ΑΡΙΣΤΟΤΕΛΗΣ', schoolTitle: 'ΜΗΧ. ΗΛ. ΥΠΟΛΟΓΙΣΤΩΝ & ΠΛΗΡ/ΚΗΣ ΠΑΤΡΑΣ' },
  { lastName: 'ΝΑΣΗ', firstName: 'ΕΡΜΙΟΝΗ', schoolTitle: 'ΔΙΑΤΡΟΦΗΣ & ΔΙΑΙΤΟΛΟΓΙΑΣ ΣΗΤΕΙΑΣ' },
  { lastName: 'ΝΑΣΤΟΣ', firstName: 'ΣΟΦΟΚΛΗΣ', schoolTitle: 'ΗΛΕΚΤΡΟΛΟΓΩΝ ΜΗΧΑΝΙΚΩΝ ΠΑΤΡΑΣ' },
  { lastName: 'ΝΙΚΟΛΛΟΥ', firstName: 'ΓΕΩΡΓΙΑ', schoolTitle: 'ΡΑΔΙΟΛΟΓΙΑΣ ΚΑΙ ΑΚΤΙΝΟΛΟΓΙΑΣ ΑΘΗΝΑΣ' },
  { lastName: 'ΝΤΟΥΛΑΣ', firstName: 'ΜΑΡΙΟΣ', schoolTitle: 'ΗΛΕΚΤΡ. ΜΗΧ. & ΜΗΧ. ΥΠΟΛΟΓΙΣΤΩΝ ΒΟΛΟΥ' },
  { lastName: 'ΝΤΟΥΧΑΝΙΑΡΗ', firstName: 'ΣΟΦΙΑ', schoolTitle: 'ΟΡΓ/ΣΗΣ & ΔΙΟΙΚ. ΕΠΙΧ/ΣΕΩΝ ΘΕΣΣΑΛΟΝΙΚΗΣ' },
  { lastName: 'ΠΑΝΑΓΙΩΤΟΠΟΥΛΟΥ', firstName: 'ΚΩΝ/ΝΑ ΙΩΑΝΝΑ', schoolTitle: 'ΙΑΤΡΙΚΗΣ ΑΘΗΝΑΣ' },
  { lastName: 'ΠΑΝΤΟΣ', firstName: 'ΘΩΜΑΣ', schoolTitle: 'ΠΛΗΡΟΦΟΡΙΚΗΣ & ΤΗΛΕΠΙΚΟΙΝΩΝΙΩΝ ΤΡΙΠΟΛΙΣ' },
  { lastName: 'ΠΑΠΑΓΙΑΝΝΗ', firstName: 'ΔΗΜΗΤΡΑ', schoolTitle: 'ΧΗΜΕΙΑΣ ΠΑΤΡΑΣ' },
  { lastName: 'ΠΑΠΑΓΙΑΝΝΗΣ', firstName: 'ΚΩΝ/ΝΟΣ', schoolTitle: 'ΗΛΕΚΤΡΟΛΟΓΩΝ ΜΗΧΑΝΙΚΩΝ Τ.Ε. ΚΑΒΑΛΑΣ' },
  { lastName: 'ΠΑΠΑΜΙΧΑΗΛ', firstName: 'ΑΛΕΞΑΝΔΡΑ', schoolTitle: 'ΓΕΩΠΟΝΙΑΣ ΘΕΣΣΑΛΟΝΙΚΗΣ' },
  { lastName: 'ΠΑΠΠΑΣ', firstName: 'ΚΩΝ/ΝΟΣ ΒΑΣΙΛΕΙΟΣ', schoolTitle: 'ΔΙΟΙΚ. ΕΠΙΧ. ΑΓΡΟΤΙΚΩΝ ΠΡΟΪΟΝΤΩΝ ΑΓΡΙΝΙΟΥ' },
  { lastName: 'ΠΑΡΡΑΣ', firstName: 'ΟΔΥΣΣΕΥΣ', schoolTitle: 'ΕΠΙΣΤ. ΕΚΠ/ΣΗΣ ΠΡΟΣΧΟΛΙΚΗΣ ΑΓΩΓΗΣ ΑΛΕΞΑΝΔΡΟΥΠΟΛΗΣ' },
  { lastName: 'ΠΡΙΝΤΖΙΟΥ', firstName: 'ΚΛΕΟΠΑΤΡΑ', schoolTitle: 'ΠΟΛΙΤΙΚΩΝ ΜΗΧΑΝΙΚΩΝ ΠΑΤΡΑΣ' },
  { lastName: 'ΡΙΖΟΥ', firstName: 'ΕΥΓΕΝΙΑ', schoolTitle: 'ΓΕΩΠΟΝΙΑΣ ΘΕΣΣΑΛΟΝΙΚΗΣ' },
  { lastName: 'ΡΟΚΟΜΟΥ', firstName: 'ΒΑΣΙΛΙΚΗ', schoolTitle: 'ΚΤΗΝΙΑΤΡΙΚΗΣ ΘΕΣΣΑΛΟΝΙΚΗΣ' },
  { lastName: 'ΡΟΥΜΕΛΙΩΤΗ', firstName: 'ΚΩΝ/ΝΑ', schoolTitle: 'ΤΕΧΝΙΚΩΝ ΥΠΑΞ/ΚΩΝ ΑΕΡΟΠΟΡΙΑΣ (ΣΤΥΑ)' },
  { lastName: 'ΣΑΚΚΑ', firstName: 'ΧΡΥΣΑΝΘΗ-ΝΕΦ.', schoolTitle: 'ΜΗΧ. ΗΛΕΚΤΡΟΝΙΚΩΝ & ΠΛΗΡΟΦΟΡΙΚΗΣ ΘΕΣ/ΚΗΣ' },
  { lastName: 'ΣΙΜΕΝΤΖΟΥΡΗ', firstName: 'ΚΩΝΣΤΑΝΤΙΝΙΑ', schoolTitle: 'ΔΙΟΙΚΗΣΗΣ ΕΠΙΧΕΙΡΗΣΕΩΝ ΑΘΗΝΑΣ' },
  { lastName: 'ΣΙΩΖΟΥ', firstName: 'ΑΙΚΑΤΕΡΙΝΗ', schoolTitle: 'ΧΗΜΕΙΑΣ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'ΣΟΥΚΗΣ', firstName: 'ΒΑΣΙΛΕΙΟΣ', schoolTitle: 'ΛΟΓΙΣΤΙΚΗΣ & ΧΡΗΜ/ΚΗΣ ΚΟΖΑΝΗΣ' },
  { lastName: 'ΣΤΑΜΟΥ', firstName: 'ΑΓΓΕΛΙΚΗ', schoolTitle: 'ΧΗΜΙΚΩΝ ΜΗΧΑΝΙΚΩΝ ΠΑΤΡΑΣ' },
  { lastName: 'ΣΤΕΡΓΙΟΥ', firstName: 'ΧΡΥΣΑΝΘΗ', schoolTitle: 'ΜΑΘΗΜΑΤΙΚΩΝ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'ΣΧΟΛΕΚΤΗ', firstName: 'ΔΗΜΗΤΡΑ', schoolTitle: 'ΝΟΜΙΚΗ ΘΕΣΣΑΛΟΝΙΚΗΣ' },
  { lastName: 'ΣΧΟΡΤΣΙΑΝΙΤΗ', firstName: 'ΣΟΦΙΑ ΝΑΤΑΛΙΑ', schoolTitle: 'ΧΗΜΙΚΩΝ ΜΗΧΑΝΙΚΩΝ ΘΕΣΣΑΛΟΝΙΚΗΣ' },
  { lastName: 'ΤΑΓΚΑΡΕΛΗΣ', firstName: 'ΛΑΜΠΡΟΣ', schoolTitle: 'ΜΗΧΑΝΙΚΩΝ ΠΛΗΡΟΦΟΡΙΚΗΣ Τ.Ε. ΑΡΤΑΣ' },
  { lastName: 'ΤΑΛΛΑΡΟΥ', firstName: 'ΘΕΟΔΩΡΑ', schoolTitle: 'ΚΟΙΝΩΝΙΚΗΣ & ΕΚΠΑΙΔΕΥΤΙΚΗΣ ΠΟΛΙΤΙΚΗΣ ΚΟΡΙΝΘΟΥ' },
  { lastName: 'ΤΑΣΟΥΛΑΣ', firstName: 'ΛΕΩΝΙΔΑΣ', schoolTitle: 'ΙΣΤΟΡΙΑΣ & ΕΘΝΟΛΟΓΙΑΣ ΚΟΜΟΤΙΝΗΣ' },
  { lastName: 'ΤΑΤΣΗ', firstName: 'ΑΛΚΗΣΤΙΣ', schoolTitle: 'ΠΑΙΔΑΓΩΓΙΚΟ ΔΗΜ. ΕΚΠ/ΣΗΣ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'ΤΑΤΣΗΣ', firstName: 'ΑΛΕΞΑΝΔΡΟΣ', schoolTitle: 'ΦΥΣΙΚΗΣ ΠΑΤΡΑΣ' },
  { lastName: 'ΤΑΧΟΥ', firstName: 'ΕΥΓΕΝΙΑ', schoolTitle: 'ΜΗΧ. ΕΠΙΣΤΗΜΗΣ ΥΛΙΚΩΝ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'ΤΖΙΜΑ', firstName: 'ΧΡΙΣΤΙΝΑ', schoolTitle: 'ΙΑΤΡΙΚΗ ΘΕΣΣΑΛΟΝΙΚΗΣ' },
  { lastName: 'ΤΖΟΥΜΑΚΑ', firstName: 'ΒΑΣΙΛΙΚΗ', schoolTitle: 'ΔΗΜΟΣΙΟΓΡΑΦΙΑΣ & ΜΜ.Ε. ΘΕΣΣΑΛΟΝΙΚΗΣ' },
  { lastName: 'ΤΖΟΥΜΑΝΙΚΑΣ', firstName: 'ΓΕΩΡΓΙΟΣ', schoolTitle: 'ΕΠΙΣΤ. ΦΥΣΙΚΗΣ ΑΓΩΓΗΣ & ΑΘΛΗΤΙΣΜΟΥ ΚΟΜΟΤΗΝΗΣ' },
  { lastName: 'ΤΖΟΥΡΜΑΝΑ', firstName: 'ΓΕΩΡΓΙΑ', schoolTitle: 'ΦΥΣΙΚΗΣ ΠΑΤΡΑΣ' },
  { lastName: 'ΤΡΑΧΑΝΑ', firstName: 'ΔΗΜΗΤΡΑ', schoolTitle: 'ΟΡΥΚΤΩΝ ΠΟΡΩΝ & ΔΙΟΙΚ. ΕΠΙΧ/ΣΕΩΝ ΘΕΣΣΑΛΟΝΙΚΗΣ' },
  { lastName: 'ΤΣΑΛΑΠΑΤΗ', firstName: 'ΠΑΝΑΓΙΩΤΑ', schoolTitle: 'ΔΙΟΙΚΗΣΗΣ ΕΠΙΧΕΙΡΗΣΕΩΝ ΛΕΥΚΑΔΑΣ' },
  { lastName: 'ΤΣΙΑΤΣΟΥΛΗ', firstName: 'ΑΝΤΙΓΟΝΗ', schoolTitle: 'ΕΛΛΗΝΙΚΗΣ ΦΙΛΟΛΟΓΙΑΣ ΚΟΜΟΤΗΝΗΣ' },
  { lastName: 'ΤΣΩΛΑΣ', firstName: 'ΝΙΚΟΛΑΟΣ', schoolTitle: 'ΑΣΤΥΦΥΛΑΚΩΝ' },
  { lastName: 'ΦΙΛΙΠΠΟΥ', firstName: 'ΕΥΑΓΓΕΛΙΑ', schoolTitle: 'ΙΣΤΟΡΙΑΣ & ΑΡΧΑΙΟΛΟΓΙΑΣ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'ΦΛΟΥΔΑΣ', firstName: 'ΗΛΙΑΣ', schoolTitle: 'ΚΙΝΗΜΑΤΟΓΡΑΦΟΥ ΘΕΣΣΑΛΟΝΙΚΗΣ' },
  { lastName: 'ΦΟΥΚΑΣ', firstName: 'ΠΑΥΛΟΣ', schoolTitle: 'ΠΟΛΙΤΙΚΩΝ ΜΗΧΑΝΙΚΩΝ ΒΟΛΟΥ' },
  { lastName: 'ΦΩΤΗ', firstName: 'ΜΑΡΙΝΑ', schoolTitle: 'ΞΕΝ.ΓΛ.ΜΕΤΑΦΡ & ΔΙΕΡΜ. ΚΕΡΚΥΡΑΣ' },
  { lastName: 'ΧΑΡΑΛΑΜΠΗΣ', firstName: 'ΠΑΝΑΓΙΩΤΗΣ', schoolTitle: 'ΜΗΧΑΝΙΚΩΝ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΑΝΙΩΝ' },
  { lastName: 'ΧΑΡΙΣΗ', firstName: 'ΕΥΑΓΓΕΛΙΑ', schoolTitle: 'ΠΑΙΔΑΓΩΓΙΚΟ ΔΗΜ. ΕΚΠ/ΣΗΣ ΑΛΕΞ/ΠΟΛΗΣ' },
  { lastName: 'ΧΑΡΙΤΟΥ', firstName: 'ΟΛΓΑ', schoolTitle: 'ΦΑΡΜΑΚΕΥΤΙΚΗΣ ΠΑΤΡΑΣ' },
  { lastName: 'ΧΡΗΣΤΟΠΑΝΟΥ', firstName: 'ΒΑΣΙΛΕΙΟΣ', schoolTitle: 'ΜΗΧΑΝΟΛΟΓΩΝ ΜΗΧΑΝΙΚΩΝ ΘΕΣ/ΝΙΚΗΣ' },
  { lastName: 'ΧΡΗΣΤΟΥ', firstName: 'ΚΛΑΟΥΝΤΙΑ', schoolTitle: 'ΔΙΟΙΚΗΣΗΣ ΕΠΙΧΕΙΡΗΣΕΩΝ ΚΟΖΑΝΗΣ' },
];

export const students2015: Student[] = [
  { lastName: 'ΑΘΑΝΑΣΙΑΔΗ', firstName: 'ΛΑΜΠΡΙΝΗ', schoolTitle: 'ΜΗΧΑΝΟΛΟΓΩΝ ΜΗΧΑΝΙΚΩΝ ΚΟΖΑΝΗ' },
  { lastName: 'ΑΝΑΣΤΑΣΙΟΥ', firstName: 'ΙΩΑΝΝΑ', schoolTitle: 'ΕΚΠΑΙΔ. & ΚΟΙΝΩΝΙΚΗΣ ΠΟΛΙΤΙΚΗΣ ΘΕΣΣΑΛΟΝΙΚΗ' },
  { lastName: 'ΑΝΤΩΝΙΟΥ', firstName: 'ΒΑΣΙΛΙΚΗ', schoolTitle: 'ΧΗΜΕΙΑΣ ΙΩΑΝΝΙΝΑ' },
  { lastName: 'ΑΣΠΡΟΠΟΤΑΜΙΤΗ', firstName: 'ΙΩΑΝΝΑ', schoolTitle: 'ΜΑΘΗΜΑΤΙΚΩΝ ΕΦΑΡΜ ΜΑΘΗΜΑΤΙΚΩΝ ΗΡΑΚΛΕΙΟ' },
  { lastName: 'ΒΑΡΗΣ', firstName: 'ΛΑΜΠΡΟΣ', schoolTitle: 'ΔΙΟΙΚΗΤΙΚΗΣ ΕΠΙΣΤΗΜΗΣ Η ΤΕΧΝΟΛΟΓΙΑΣ ΑΘΗΝΑ' },
  { lastName: 'ΒΑΣΙΛΑΚΗ', firstName: 'ΕΙΡΗΝΗ', schoolTitle: 'ΝΟΣΗΛΕΥΤΙΚΗΣ ΠΑΤΡΑ' },
  { lastName: 'ΒΕΝΤΙΣΤΑ', firstName: 'ΕΥΑΓΓΕΛΙΑ', schoolTitle: 'ΜΗΧΑΝΟΛΟΓΩΝ & ΑΕΡΟΝΑΥΠΗΓΩΝ ΜΗΧΑΝΙΚΩΝ ΠΑΤΡΑ' },
  { lastName: 'ΒΕΤΣΙΟΥ', firstName: 'ΧΡΙΣΤΙΝΑ', schoolTitle: 'ΠΟΛΙΤΙΚΩΝ ΜΗΧΑΝΙΚΩΝ ΓΕ ΠΑΤΡΑ' },
  { lastName: 'ΒΛΑΧΟΥ', firstName: 'ΕΥΑ', schoolTitle: 'ΦΥΣΙΚΗΣ ΠΑΤΡΑ' },
  { lastName: 'ΒΟΥΒΑΛΗΣ', firstName: 'ΔΗΜΗΤΡΙΟΣ', schoolTitle: 'ΟΙΚΟΝΟΜΙΚΩΝ ΕΠΙΣΤΗΜΩΝ ΙΩΑΝΝΙΝΑ' },
  { lastName: 'ΓΕΩΡΓΑΚΗ', firstName: 'ΜΑΡΙΑ', schoolTitle: 'ΓΕΩΛΟΓΙΑΣ ΠΑΤΡΑ' },
  { lastName: 'ΓΕΩΡΓΑΚΟΠΟΥΛΟΥ', firstName: 'ΙΩΑΝΝΑ', schoolTitle: 'ΔΙΑΤΡΟΦΗΣ & ΔΙΑΙΤΟΛΟΓΙΑΣ ΚΑΡΔΙΤΣΑ' },
  { lastName: 'ΓΕΩΡΓΙΟΥ', firstName: 'ΑΛΕΞΑΝΔΡΑ', schoolTitle: 'ΚΤΗΝΙΑΤΡΙΚΗΣ ΚΑΡΔΙΤΣΑ' },
  { lastName: 'ΓΕΩΡΓΟΥΛΑ', firstName: 'ΓΕΩΡΓΙΑ', schoolTitle: 'ΠΑΙΔΑΓΩΓΙΚΟ ΔΗΜ. ΕΚΠΑΙΔΕΥΣΗΣ ΙΩΑΝΝΙΝΑ' },
  { lastName: 'ΓΚΕΤΣΗΣ', firstName: 'ΑΓΓΕΛΟΣ', schoolTitle: 'ΜΗΧΑΝΙΚΩΝ ΑΥΤΟΜΑΤΙΣΜΟΥ ΤΕ ΠΕΙΡΑΙΑ' },
  { lastName: 'ΓΚΟΛΟΜΑΖΟΥ', firstName: 'ΣΤΑΜΑΤΙΑ-ΝΙ', schoolTitle: 'ΜΑΘΗΜΑΤΙΚΩΝ&ΕΦΑΡΜ.ΜΑΘΗΜΑΤΙΚΩΝ ΗΡΑΚΛΕΙΟ' },
  { lastName: 'ΓΚΟΤΟΒΟΥ', firstName: 'ΙΛΙΑΔΑ ΝΑΤΑΛΙΑ', schoolTitle: 'ΠΛΗΡΟΦΟΡΙΚΗΣ ΘΕΣΣΑΛΟΝΙΚΗ' },
  { lastName: 'ΓΚΟΥΛΙΑΡΑΣ', firstName: 'ΚΩΝΣΤΑΝΤΙΝΟΣ', schoolTitle: 'ΗΛΕΚΤΡΟΛΟΓΩΝ ΜΗΧΑΝΙΚΩΝ ΘΕΣΣΑΛΟΝΙΚΗ' },
  { lastName: 'ΓΟΥΣΙΑΣ', firstName: 'ΓΕΩΡΓΙΟΣ', schoolTitle: 'ΟΙΚΟΝΟΜΙΚΩΝ ΕΠΙΣΤΗΜΩΝ ΑΘΗΝΑ' },
  { lastName: 'ΔΕΡΒΙΛΗΣ', firstName: 'ΓΕΩΡΓΙΟΣ', schoolTitle: 'ΛΟΓΙΣΤΙΚΗΣ & ΧΡΗΜΑΤΟΟΙΚΟΝΟΜΙΚΗΣ ΠΡΕΒΕΖΑ' },
  { lastName: 'ΔΗΜΟΣ', firstName: 'ΛΑΜΠΡΟΣ', schoolTitle: 'ΧΡΗΜΑΤΟΟΙΚΟΝΟΜΙΚΗΣ & ΤΡΑΠΕΖΙΚΗΣ ΔΙΟΙΚΗΤΙΚΗΣ ΠΕΙΡΑΙΑ' },
  { lastName: 'ΔΙΑΚΟΓΙΑΝΝΗ', firstName: 'ΑΓΓΕΛΙΚΗ', schoolTitle: 'ΛΟΓΙΣΤΙΚΗΣ & ΧΡΗΜΑΤΟΟΙΚΟΝΟΜΙΚΗΣ ΠΡΕΒΕΖΑΣ' },
  { lastName: 'ΔΡΑΚΟΥ', firstName: 'ΧΡΙΣΤΙΝΑ', schoolTitle: 'ΔΙΟΙΚΗΣΗΣ ΕΠΙΧΕΙΡΗΣΕΩΝ ΠΑΤΡΑ' },
  { lastName: 'ΔΡΑΚΟΥ', firstName: 'ΧΡΥΣΟΥΛΑ', schoolTitle: 'ΓΕΩΠΟΝΙΑΣ ΑΡΤΑΣ' },
  { lastName: 'ΕΥΘΥΜΙΟΥ', firstName: 'ΝΙΚΟΛΑΟΣ', schoolTitle: 'ΛΟΓΙΣΤΙΚΗΣ & ΧΡΗΜΑΤΟΟΙΚΟΝΟΜΙΚΗΣ ΘΕΣΣΑΛΟΝΙΚΗ' },
  { lastName: 'ΖΑΧΑΡΗΣ', firstName: 'ΑΛΕΞΑΝΔΡΟΣ', schoolTitle: 'ΕΠΙΣΤΗΜΗΣ ΦΥΤΙΚΗΣ ΠΑΡΑΓΩΓΗΣ ΑΘΗΝΑ' },
  { lastName: 'ΖΗΣΗΣ', firstName: 'ΠΑΝΑΓΙΩΤΗΣ', schoolTitle: 'ΟΡΓΑΝΩΣΗΣ & ΔΙΟΙΚΗΣΗΣ ΕΠΙΧΕΙΡΗΣΕΩΝ ΘΕΣΣΑΛΟΝΙΚΗ' },
  { lastName: 'ΚΑΚΚΙΩΝΗΣ', firstName: 'ΒΑΣΙΛΕΙΟΣ', schoolTitle: 'ΜΗΧ. ΗΛ. ΥΠ. ΚΑΙ ΠΛΗΡΟΦΟΡΙΚΗΣ, ΙΩΑΝΝΙΝΑ' },
  { lastName: 'ΚΑΚΟΛΥΡΗΣ', firstName: 'ΙΩΑΝΝΗΣ', schoolTitle: 'ΔΙΟΙΚΗΣΗΣ ΕΠΙΧΕΙΡΗΣΕΩΝ ΘΕΣΣΑΛΟΝΙΚΗ' },
  { lastName: 'ΚΑΛΑΜΠΟΚΗ', firstName: 'ΘΕΡΙΣΙΑ', schoolTitle: 'ΟΙΚΟΝΟΜΙΚΩΝ ΕΠΙΣΤΗΜΩΝ ΡΕΘΥΜΝΟ' },
  { lastName: 'ΚΑΛΑΜΠΟΚΗ', firstName: 'ΕΥΑΓΓΕΛΙΑ', schoolTitle: 'ΙΑΤΡΙΚΗ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'ΚΑΛΙΑΡΝΤΑΣ', firstName: 'ΧΡΗΣΤΟΣ', schoolTitle: 'ΠΟΛΙΤΙΚΩΝ ΜΗΧΑΝΙΚΩΝ ΞΑΝΘΗ' },
  { lastName: 'ΚΑΠΟΔΙΣΤΡΙΑΣ', firstName: 'ΙΩΑΝΝΗΣ', schoolTitle: 'ΔΙΟΙΚΗΣΗ ΕΠΙΧΕΙΡΗΣΕΩΝ ΠΑΤΡΑ' },
  { lastName: 'ΚΑΡΑΓΙΑΝΝΗΣ', firstName: 'ΔΗΜΗΤΡΙΟΣ', schoolTitle: 'ΟΔΟΝΤΙΑΤΡΙΚΗΣ ΘΕΣΣΑΛΟΝΙΚΗ' },
  { lastName: 'ΚΑΡΑΚΩΣΤΑ', firstName: 'ΑΦΡΟΔΙΤΗ', schoolTitle: 'ΚΤΗΝΙΑΤΡΙΚΗΣ ΚΑΡΔΙΤΣΑ' },
  { lastName: 'ΚΑΡΑΚΩΣΤΑΣ', firstName: 'ΧΡΗΣΤΟΣ', schoolTitle: 'ΔΑΣΟΠΟΝΙΑΣ & ΔΙΑΧΕΙΡΙΣΗΣ ΦΥΣ. ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΚΑΡΠΕΝΗΣΙ' },
  { lastName: 'ΚΑΡΑΜΠΑ', firstName: 'ΒΑΣΙΛΙΚΗ', schoolTitle: 'ΦΑΡΜΑΚΕΥΤΙΚΗΣ ΠΑΤΡΑ' },
  { lastName: 'ΚΑΤΣΙΓΙΑΝΝΗ', firstName: 'ΜΑΡΙΑ', schoolTitle: 'ΟΙΚΟΝΟΜΙΚΩΝ ΕΠΙΣΤΗΜΩΝ ΙΩΑΝΝΙΝΑ' },
  { lastName: 'ΚΟΡΔΑΛΗ', firstName: 'ΑΙΚΑΤΕΡΙΝΗ', schoolTitle: 'ΜΗΧΑΝΙΚΩΝ ΧΩΡΟΤΑΞΙΑΣ & ΑΝΑΠΤΥΞΗΣ ΘΕΣΣΑΛΟΝΙΚΗ' },
  { lastName: 'ΚΟΥΡΕΛΗ', firstName: 'ΣΑΒΒΟΥΛΑ', schoolTitle: 'ΟΡΓΑΝΩΣΗΣ & ΔΙΟΙΚΗΣΗΣ ΕΠΙΧΕΙΡΗΣΕΩΝ ΘΕΣΣΑΛΟΝΙΚΗ' },
  { lastName: 'ΚΩΤΣΗ', firstName: 'ΔΗΜΗΤΡΑ', schoolTitle: 'ΦΙΛΟΛΟΓΙΑΣ ΙΩΑΝΝΙΝΑ' },
  { lastName: 'ΛΑΜΠΡΗ', firstName: 'ΚΑΛΙΡΡΟΗ', schoolTitle: 'ΔΙΟΙΚΗΣΗΣ ΕΠΙΧΕΙΡΗΣΕΩΝ ΛΕΥΚΑΔΑ' },
  { lastName: 'ΛΕΚΟΣ', firstName: 'ΙΑΣΩΝ', schoolTitle: 'ΙΑΤΡΙΚΗΣ ΘΕΣΣΑΛΟΝΙΚΗ' },
  { lastName: 'ΛΙΑΡΟΚΑΠΗ', firstName: 'ΕΥΤΥΧΙΑ', schoolTitle: 'ΟΡΓΑΝΩΣΗΣ & ΔΙΟΙΚΗΣΗΣ ΕΠΙΧΕΙΡΗΣΕΩΝ ΑΘΗΝΑ' },
  { lastName: 'ΛΥΚΑ', firstName: 'ΝΙΟΒΗ', schoolTitle: 'ΒΙΟΛΟΓΙΚΩΝ ΕΦΑΡΜΟΓΩΝΑ ΤΕΧΝΟΛΟΓΩΝ ΙΩΑΝΝΙΝΑ' },
  { lastName: 'ΛΥΚΚΑΣ', firstName: 'ΗΛΙΑΣ', schoolTitle: 'ΗΛΕΚΤΡΟΛΟΓΩΝ ΜΗΧΑΝΙΚΩΝ ΤΕ ΧΑΛΚΙΔΑ' },
  { lastName: 'ΜΑΡΟΣ', firstName: 'ΑΛΕΞΑΝΔΡΟΣ', schoolTitle: 'ΟΙΚΟΝΟΜΙΚΩΝ ΕΠΙΣΤΗΜΩΝ ΘΕΣΣΑΛΟΝΙΚΗ' },
  { lastName: 'ΜΕΙΝΤΗ', firstName: 'ΑΛΕΞ', schoolTitle: 'ΔΙΟΙΚΗΣΗΣ ΕΠΙΧΕΙΡΗΣΕΩΝ ΛΕΥΚΑΔΑ' },
  { lastName: 'ΜΗΤΣΙΟΥ', firstName: 'ΒΑΣΙΛΙΚΗ-ΘΕΟΔΩΡΑ', schoolTitle: 'ΛΟΓΙΣΤΙΚΗΣ & ΧΡΗΜΑΤΟΟΙΚΟΝΟΜΙΚΗΣ ΠΡΕΒΕΖΑ' },
  { lastName: 'ΜΙΝΟΥ', firstName: 'ΕΛΕΝΗ', schoolTitle: 'ΟΙΚΟΝΟΜΙΚΩΝ ΕΠΙΣΤΗΜΩΝ ΒΟΛΟΣ' },
  { lastName: 'ΜΟΥΣΑΒΕΡΕ', firstName: 'ΑΓΓΕΛΙΚΗ', schoolTitle: 'ΑΡΧΙΤΕΚΤΟΝΩΝ ΜΗΧΑΝΙΚΩΝ ΧΑΝΙΑ' },
  { lastName: 'ΜΠΑΚΑΓΙΑΝΝΗ', firstName: 'ΜΑΡΙΑ', schoolTitle: 'ΤΕΧΝΟΛΟΓΙΑΣ ΤΡΟΦΙΜΩΝ ΚΑΛΑΜΑΤΑ' },
  { lastName: 'ΜΠΑΛΑΣΚΑΣ', firstName: 'ΚΩΝΣΤΑΝΤΙΝΟΣ', schoolTitle: 'ΒΙΟΜΗΧΑΝΙΚΗΣ ΔΙΟΙΚΗΣΗΣ ΔΙΟΙΚΗΣΗΣ ΠΕΙΡΑΙΑΣ' },
  { lastName: 'ΜΠΑΦΑ', firstName: 'ΚΩΝΣΤΑΝΤΙΝΑ', schoolTitle: 'ΙΑΤΡΙΚΗΣ ΙΩΑΝΝΙΝΑ' },
  { lastName: 'ΜΠΕΛΗ', firstName: 'ΒΑΣΙΛΙΚΗ', schoolTitle: 'ΙΑΤΡΙΚΗΣ ΑΛΕΞΑΝΔΡΟΥΠΟΛΗΣ' },
  { lastName: 'ΜΠΟΥΓΑΣ', firstName: 'ΠΑΥΛΟΣ', schoolTitle: 'ΠΟΛΙΤΙΚΩΝ ΜΗΧΑΝΙΚΩΝ ΤΕ ΘΕΣΣΑΛΟΝΙΚΗ' },
  { lastName: 'ΜΠΟΥΚΑ', firstName: 'ΕΛΕΝΗ', schoolTitle: 'ΓΕΩΠΟΝΙΑΣ, ΙΧΘΥΟΛΟΠΑΣΥΔΑΤΙΝΟΥ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΒΟΛΟΣ' },
  { lastName: 'ΜΠΟΥΡΑΣ', firstName: 'ΑΝΔΡΕΑΣ', schoolTitle: 'ΦΥΣΙΚΗΣ ΠΑΤΡΑ' },
  { lastName: 'ΜΠΡΑΝΙΚΑΣ', firstName: 'ΝΙΚΟΛΑΟΣ', schoolTitle: 'ΜΗΧ. ΗΛ.ΥΠ.ΠΛΗΡΟΦΟΡΙΚΗΣ ΠΑΤΡΑ' },
  { lastName: 'ΝΤΑΒΡΗΣ', firstName: 'ΟΝΟΥΦΡΙΟΣ', schoolTitle: 'ΜΗΧ. ΠΛΗΡΟΦΟΡΙΑΚΩΝ ΕΠΙΚΟΙΝΩΝΙΑΚΩΝ ΣΥΣΤΗΜΑΤΩΝ ΣΑΜΟΣ' },
  { lastName: 'ΟΙΚΟΝΟΜΟΥ', firstName: 'ΣΤΕΛΛΑ-ΜΑΥΡΕΤΑ', schoolTitle: 'ΛΟΓΙΣΤΙΚΗΣ ΚΑΙ ΧΡΗΜΑΤΟΟΙΚΟΝΟΜΙΚΗΣ ΑΘΗΝΑ' },
  { lastName: 'ΠΑΠΑΒΑΓΓΕΛΗΣ', firstName: 'ΛΑΜΠΡΟΣ', schoolTitle: 'ΜΟΝΙΜΩΝ ΥΠΑΞΙΩΜΑΤΙΚΩΝ ΝΑΥΤΙΚΟΥ Σ.Μ.Υ.Ν.' },
  { lastName: 'ΠΑΠΑΛΕΞΗ', firstName: 'ΧΡΙΣΤΙΝΑ', schoolTitle: 'ΔΙΑΤΡΟΦΗΣ ΚΑΙ ΔΙΑΙΤΟΛΟΓΙΑΣ ΚΑΡΔΙΤΣΑ' },
  { lastName: 'ΠΑΠΑΝΙΚΟΛΑΟΥ', firstName: 'ΒΑΣΙΛΕΙΟΣ', schoolTitle: 'ΙΣΤΟΡΙΑΣ & ΑΡΧΑΙΟΛΟΓΙΑΣ ΙΩΑΝΝΙΝΑ' },
  { lastName: 'ΠΑΠΠΑ', firstName: 'ΑΓΓΕΛΙΚΗ', schoolTitle: 'ΗΛΕΚΤΡΟΛΟΓΩΝ ΜΗΧ. ΜΗΧΑΝΙΚΩΝ ΥΠΟΛΟΓΙΣΤΩΝ ΒΟΛΟΣ' },
  { lastName: 'ΠΑΡΑΣΚΕΥΑΚΗ', firstName: 'ΕΥΑΓΓΕΛΙΑ', schoolTitle: 'ΔΙΟΙΚΗΣΗ ΕΠΙΧΕΙΡΗΣΕΩΝ ΠΑΤΡΑ' },
  { lastName: 'ΠΑΡΑΣΚΕΥΑΚΗ', firstName: 'ΕΙΡΗΝΗ', schoolTitle: 'ΠΟΛΙΤΙΚΩΝ ΜΗΧΑΝΙΚΩΝ ΤΕ ΠΑΤΡΑ' },
  { lastName: 'ΡΟΥΜΕΛΙΩΤΗ', firstName: 'ΚΩΝΣΤΑΝΤΙΝΑ', schoolTitle: 'ΟΙΚΟΝΟΜΙΚΩΝ ΕΠΙΣΤΗΜΩΝ ΙΩΑΝΝΙΝΑ' },
  { lastName: 'ΣΙΛΙΩΝΗΣ', firstName: 'ΝΙΚΟΛΑΟΣ', schoolTitle: 'ΝΑΥΠΗΓΩΝ ΜΗΧΑΝΟΛΟΓΩΝ ΜΗΧΑΝΙΚΩΝ ΑΘΗΝΑ' },
  { lastName: 'ΣΙΟΓΚΑ', firstName: 'ΖΩΗ', schoolTitle: 'ΕΠΙΣΤΗΜΗΣ ΦΥΣ ΑΓΩΓΗΣΑ ΑΘΛΗΤΙΣΜΟΥ ΘΕΣΣΑΛΟΝΙΚΗ' },
  { lastName: 'ΣΙΟΓΚΑΣ', firstName: 'ΕΥΑΓΓΕΛΟΣ', schoolTitle: 'ΠΛΗΡΟΦΟΡΙΚΗΣ ΘΕΣΣΑΛΟΝΙΚΗ' },
  { lastName: 'ΣΚΕΝΤΟΥ', firstName: 'ΠΑΡΑΣΚΕΥΗ-', schoolTitle: 'ΜΥΡ.ΠΡΟΓΡΑΜΜΑ ΔΙΑΧΕΙΡΙΣΗΣ ΕΚΚΛΗΣΙΑΣΤΙΚΩΝ ΚΕΙΜΗΛΙΩΝ ΑΘΗΝΑΣ' },
  { lastName: 'ΣΤΑΣΙΝΟΣ', firstName: 'ΛΑΜΠΡΟΣ', schoolTitle: 'ΟΙΚΟΝΟΜΙΚΩΝ ΕΠΙΣΤΗΜΩΝ ΑΘΗΝΑ' },
  { lastName: 'ΣΤΑΣΙΝΟΥ', firstName: 'ΟΛΓΑ', schoolTitle: 'ΝΟΣΗΛΕΥΤΙΚΗ ΙΩΑΝΝΙΝΩΝ' },
  { lastName: 'ΣΤΑΥΡΟΣ', firstName: 'ΝΙΚΟΛΑΟΣ', schoolTitle: 'ΜΗΧΑΝΙΚΩΝ ΠΛΗΡΟΦΟΡΙΚΗΣ ΤΕ ΑΡΤΑΣ' },
  { lastName: 'ΣΥΓΙΖΗΣ', firstName: 'ΑΛΕΞΑΝΔΡΟΣ', schoolTitle: 'ΠΟΝΤΙΚΩΝ ΜΗΧΑΝΙΚΩΝ ΒΟΛΟΣ' },
  { lastName: 'ΣΧΙΣΜΕΝΟΥ', firstName: 'ΒΑΣΙΛΙΚΗ', schoolTitle: 'ΧΡΗΜΑΤΟΟΙΚΟΝΟΜΙΚΗΣ & ΛΟΓΙΣΤΙΚΗΣ ΠΑΤΡΑΣ' },
  { lastName: 'ΤΑΤΣΗ', firstName: 'ΝΙΚΟΛΕΤΑ', schoolTitle: 'ΔΙΟΙΚΗΣΗ ΕΠΙΧΕΙΡΗΣΕΩΝ ΧΙΟΣ' },
  { lastName: 'ΤΡΙΦΙ', firstName: 'ΒΑΓΓΕΛ', schoolTitle: 'ΔΙΟΙΚΗΣΗΣ ΕΠΙΧΕΙΡΗΣΕΩΝ ΠΑΤΡΑ' },
  { lastName: 'ΤΣΙΑΜΠΟΥΛΑΣ', firstName: 'ΑΠΟΣΤΟΛΟΣ', schoolTitle: 'ΔΙΟΙΚΗΣΗΣ ΕΠΙΧΕΙΡΗΣΕΩΝ ΠΑΤΡΑ' },
  { lastName: 'ΤΣΙΡΚΑ', firstName: 'ΧΡΙΣΤΙΑΝΑ', schoolTitle: 'ΜΗΧ.ΠΑΝΙΡ. ΔΙΑΚΩΝ ΣΥΣΤΗΜΑΤΩΝ ΣΑΜΟΣ' },
  { lastName: 'ΦΑΝΤΗΣ', firstName: 'ΑΓΓΕΛΟΣ', schoolTitle: 'ΜΟΝΙΜΩΝ ΥΠΑΞΙΩΜΑΤΙΚΩΝ ΝΑΥΤΙΚΟΥ Σ.Μ.Υ.Ν.' },
  { lastName: 'ΦΛΩΡΟΥ', firstName: 'ΑΙΚΑΤΕΡΙΝΗ', schoolTitle: 'ΜΗΧ.ΗΛ. ΥΠ.ΚΑΙ ΠΛΗΡΟΦΟΡΙΚΗΣ ΠΑΤΡΑ' },
  { lastName: 'ΦΟΥΝΤΑ', firstName: 'ΕΛΕΥΘΕΡΙΑ', schoolTitle: 'ΜΗΧΑΝΙΚΩΝ ΕΠΙΣΤΗΜΗΣ ΥΛΙΚΩΝ ΙΩΑΝΝΙΝΑ' },
  { lastName: 'ΧΟΥΛΙΑΡΑ', firstName: 'ΑΙΚΑΤΕΡΙΝΗ', schoolTitle: 'ΝΟΣΗΛΕΥΤΙΚΗΣ ΣΠΑΡΤΗ' },
  { lastName: 'ΧΡΥΣΙΚΟΥ', firstName: 'ΑΓΓΕΛΙΚΗ', schoolTitle: 'ΧΗΜΙΚΩΝ ΜΗΧΑΝΙΚΩΝ ΘΕΣΣΑΛΟΝΙΚΗ' },
];

// 2016 data - extracted from image description
export const students2016: Student[] = [
  { lastName: 'ΑΣΠΡΟΥΔΗ', firstName: 'ΛΑΜΠΡΙΝΗ', schoolTitle: 'ΜΗΧ.ΟΡΥΚΤΩΝ ΠΟΡΩΝ ΧΑΝΙΑ' },
  { lastName: 'ΒΑΣΙΛΕΙΟΥ', firstName: 'ΑΓΓΕΛΙΚΗ', schoolTitle: 'ΜΗΧ.ΤΕΧΝΟΛΟΓΙΑΣ ΠΕΤΡΕΛΑΙΟΥ & ΦΥΣΙΚΟΥ ΑΕΡΙΟΥ ΤΕ&ΜΗΧΑΝΟΛΟΓΩΝ ΜΗΧ. ΤΕ ΚΑΒΑΛΑ' },
  { lastName: 'ΒΑΣΙΛΕΙΟΥ', firstName: 'ΔΗΜΗΤΡΑ', schoolTitle: 'ΝΟΣΗΛΕΥΤΙΚΗΣ ΣΠΑΡΤΗΣ' },
  { lastName: 'ΓΑΛΗΝΑΣ', firstName: 'ΣΩΤΗΡΙΟΣ', schoolTitle: 'ΠΟΛΙΤΙΚΩΝ ΜΗΧΑΝΙΚΩΝ ΑΘΗΝΑ' },
  { lastName: 'ΓΕΩΡΓΟΠΟΥΛΟΥ', firstName: 'ΒΑΛΕΡΙΑ', schoolTitle: 'ΚΟΙΝ.ΔΙΟΙΚΗΣΗΣ & ΠΟΛΙΤΙΚΗΣ ΕΠΙΣΤΗΜΗΣ ΚΟΜΟΤΗΝΗ' },
  { lastName: 'ΓΙΑΓΛΑΡΑ', firstName: 'ΜΑΤΘΙΛΔΗ', schoolTitle: 'ΒΙΟΛΟΓΙΑΣ ΗΡΑΚΛΕΙΟ' },
  { lastName: 'ΠΑΝΝΕΛΟΥ', firstName: 'ΑΘΗΝΑ', schoolTitle: 'ΙΑΤΡΙΚΩΝ ΕΡΓΑΣΤΗΡΙΩΝ ΛΑΡΙΣΑ' },
  { lastName: 'ΠΑΝΝΟΥΛΗΣ', firstName: 'ΗΛΙΑΣ', schoolTitle: 'ΦΥΣΙΚΟΘΕΡΑΠΕΙΑΣ ΘΕΣΣΑΛΟΝΙΚΗ' },
  { lastName: 'ΓΙΩΤΗ', firstName: 'ΒΑΙΑ', schoolTitle: 'ΕΚΠΑΙΔΕΥΤΙΚΩΝ ΜΗΧΑΝΟΛΟΓΩΝ ΜΗΧΑΝΙΚΩΝ ΑΣΠΑΙΤΕ' },
  { lastName: 'ΓΚΑΒΑΠΑ', firstName: 'ΡΟΔΑΝΘΗ', schoolTitle: 'ΟΙΚΟΝΟΜΙΚΩΝ ΕΠΙΣΤΗΜΩΝ ΘΕΣΣΑΛΟΝΙΚΗ' },
  { lastName: 'ΓΚΕΤΣΗΣ', firstName: 'ΑΓΓΕΛΟΣ', schoolTitle: 'ΜΗΧ. ΠΛΗΡΟΦΟΡΙΑΚΩΝ & ΕΠΙΚΟΙΝΩΝΙΑΚΩΝ ΣΥΣΤΗΜΑΤΩΝ ΣΑΜΟΣ' },
  { lastName: 'ΓΚΟΛΟΜΑΖΟΣ', firstName: 'ΔΗΜΗΤΡΙΟΣ', schoolTitle: 'ΑΓΡΟΤΙΚΗΣ ΑΝΑΠΤΥΞΗΣ ΟΡΕΣΤΙΑΔΑ' },
  { lastName: 'ΓΡΕΤΣΙΣΤΑΣ', firstName: 'ΓΕΩΡΓΙΟΣ', schoolTitle: 'ΛΟΓΙΣΤΙΚΗΣ & ΧΡΗΜΑΤΟΟΙΚΟΝΟΜΙΚΗΣ ΘΕΣΣΑΛΟΝΙΚΗ' },
  { lastName: 'ΔΕΡΒΙΛΗΣ', firstName: 'ΓΕΩΡΓΙΟΣ', schoolTitle: 'ΔΙΟΙΚΗΣΗΣ ΕΠΙΧΕΙΡΗΣΕΩΝ ΘΕΣΣΑΛΟΝΙΚΗ' },
  { lastName: 'ΕΥΘΥΜΙΟΥ', firstName: 'ΑΝΔΡΕΑΣ', schoolTitle: 'ΔΙΟΙΚΗΣΗΣ ΕΠΙΧΕΙΡΗΣΕΩΝ ΠΡΟΪΟΝΤΩΝ & ΤΡΟΦΙΜΩΝ ΑΓΡΙΝΙΟ' },
  { lastName: 'ΕΥΘΥΜΙΟΥ', firstName: 'ΝΑΥΣΙΚΑ', schoolTitle: 'ΔΙΟΙΚΗΣΗΣ ΕΠΙΧΕΙΡΗΣΕΩΝ ΛΑΡΙΣΑ' },
  { lastName: 'ΖΗΣΗΣ', firstName: 'ΒΑΣΙΛΕΙΟΣ', schoolTitle: 'ΔΙΕΘΝΩΝ & ΕΥΡΩΠΑΪΚΩΝ ΣΠΟΥΔΩΝ ΘΕΣΣΑΛΟΝΙΚΗ' },
  { lastName: 'ΚΑΚΑΒΑΣ', firstName: 'ΓΕΩΡΓΙΟΣ', schoolTitle: 'ΜΗΧΑΝΙΚΩΝ ΠΛΗΡΟΦΟΡΙΚΗΣ ΤΕ ΚΑΒΑΛΑ' },
  { lastName: 'ΚΑΚΟΧΡΗΣΤΟΣ', firstName: 'ΠΑΝΑΠΩΤΗΣ', schoolTitle: 'ΜΗΧΑΝΟΛΟΓΩΝ ΜΗΧΑΝΙΚΩΝ ΘΕΣΣΑΛΟΝΙΚΗ' },
  { lastName: 'ΚΑΠΕΛΗ', firstName: 'ΘΕΟΔΩΡΑ', schoolTitle: 'ΚΟΙΝΩΝΙΚΗΣ ΑΝΘΡΩΠΟΛΟΓΙΑΣ & ΙΣΤΟΡΙΑΣ ΜΥΤΙΛΗΝΗ' },
  { lastName: 'ΚΑΡΑΓΕΩΡΓΟΣ', firstName: 'ΚΩΝΣΤΑΝΤΙΝΟΣ', schoolTitle: 'ΜΑΘΗΜΑΤΙΚΩΝ & ΕΦΑΡΜΟΣΜΕΝΩΝ ΜΑΘΗΜΑΤΙΚΩΝ ΗΡΑΚΛΕΙΟ' },
  { lastName: 'ΚΑΡΑΚΩΣΤΑ', firstName: 'ΑΦΡΟΔΙΤΗ', schoolTitle: 'ΧΗΜΙΚΩΝ ΜΗΧΑΝΙΚΩΝ ΠΑΤΡΑ' },
  { lastName: 'ΚΑΡΑΜΠΕΛΑΣ', firstName: 'ΕΥΑΓΓΕΛΟΣ', schoolTitle: 'ΔΙΟΙΚΗΣΗ ΕΠΙΧΕΙΡΗΣΕΩΝ ΛΕΥΚΑΔΑ' },
  { lastName: 'ΚΑΤΣΟΥΛΑΣ', firstName: 'ΑΓΓΕΛΟΣ', schoolTitle: 'ΗΛΕΚΤΡΟΛΟΓΩΝ ΜΗΧΑΝΙΚΩΝ & ΜΗΧΑΝΙΚΩΝ ΥΠΟΛΟΓΙΣΤΩΝ ΑΘΗΝΑ' },
  { lastName: 'ΚΟΠΑΝΤΗ', firstName: 'ΚΩΝΣΤΑΝΤΙΝΑ', schoolTitle: 'ΗΛΕΚΤΡΟΛΟΓΩΝ ΜΗΧ.& ΜΗΧ.ΥΠΟΛΟΓΙΣΤΩΝ ΒΟΛΟΣ' },
  { lastName: 'ΚΟΝΙΑΡΗ', firstName: 'ΠΑΝΑΓΙΩΤΑ', schoolTitle: 'ΠΟΛΙΤΙΚΩΝ ΜΗΧΑΝΙΚΩΝ ΤΕ ΘΕΣΣΑΛΟΝΙΚΗ' },
  { lastName: 'ΚΟΡΔΑΛΗ', firstName: 'ΒΑΣΙΛΙΚΗ', schoolTitle: 'ΑΡΧΙΤΕΚΤΟΝΩΝ ΜΗΧΑΝΙΚΩΝ ΙΩΑΝΝΙΝΑ' },
  { lastName: 'ΚΟΥΝΙΣΤΟΣ', firstName: 'ΙΩΑΝΝΗΣ', schoolTitle: 'ΜΗΧ.ΠΕΡΙΒΑΛΛΟΝΤΟΣ&ΜΗΧ.ΑΝΤΙΡΡΥΠΑΝΣΗΣΤ.Ε.ΚΟΖΑΝΗΣ' },
  { lastName: 'ΚΩΣΤΑΣ', firstName: 'ΧΡΗΣΤΟΣ', schoolTitle: 'ΠΟΛΙΤΙΚΩΝ ΜΗΧΑΝΙΚΩΝ ΞΑΝΘΗΣ' },
  { lastName: 'ΛΑΜΠΡΗ', firstName: 'ΚΑΛΛΙΡΡΟΗ', schoolTitle: 'ΜΗΧΑΝΙΚΩΝ ΠΛΗΡΟΦΟΡΙΚΗΣ ΤΕ ΑΡΤΑΣ' },
  { lastName: 'ΛΟΥΓΚΙΑ', firstName: 'ΑΝΔΡΙΑΝΟΣ', schoolTitle: 'ΜΗΧ.ΗΛΕΚΤΡΟΝΙΚΩΝ ΥΠΟΛΟΓΙΣΤΩΝ & ΠΛΗΡΟΦΟΡΙΚΗΣ ΠΑΤΡΑ' },
  { lastName: 'ΛΥΚΑ', firstName: 'ΝΙΟΒΗ', schoolTitle: 'ΙΑΤΡΙΚΗΣ ΙΩΑΝΝΙΝΑ' },
  { lastName: 'ΜΑΜΠΤΖΗΣ', firstName: 'ΧΡΙΣΤΙΝΑ', schoolTitle: 'ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΜΥΤΙΛΗΝΗ' },
  { lastName: 'ΜΑΝΟΣ', firstName: 'ΓΙΑΝΝΗΣ', schoolTitle: 'ΕΥΕΛΠΙΔΩΝ (ΣΣΕ) ΟΠΛΑ' },
  { lastName: 'ΜΑΡΓΩΝΗ', firstName: 'ΑΡΤΕΜΙΣ', schoolTitle: 'ΧΗΜΕΙΑΣ ΑΘΗΝΑ' },
  { lastName: 'ΜΠΙΣΚΑΝΑΚΗ', firstName: 'ΒΑΣΙΛΙΚΗ', schoolTitle: 'ΦΙΛΟΛΟΓΙΑΣ ΘΕΣΣΑΛΟΝΙΚΗ' },
  { lastName: 'ΜΠΟΥΚΑ', firstName: 'ΕΛΕΝΗ', schoolTitle: 'ΜΗΧΑΝΙΚΩΝ ΥΠΟΛΟΓΙΣΤΩΝ&ΠΛΗΡΟΦΟΡΙΚΗΣ ΙΩΑΝΝΙΝΑ' },
  { lastName: 'ΝΑΚΑΣ', firstName: 'ΚΩΝΣΤΑΝΤΙΝΟΣ', schoolTitle: 'ΗΛΕΚΤΡΟΛΟΓΩΝ ΜΗΧΑΝΙΚΩΝ & ΤΕΧΝΟΛΟΓΙΑΣ ΥΠΟΛΟΓΙΣΤΩΝ ΠΑΤΡΑ' },
  { lastName: 'ΠΑΠΑΒΑΓΓΕΛΗΣ', firstName: 'ΠΑΝΑΓΙΩΤΗΣ', schoolTitle: 'ΜΗΧΑΝΟΛΟΓΩΝ ΜΗΧΑΝΙΚΩΝ ΤΕ ΧΑΛΚΙΔΑ' },
  { lastName: 'ΠΑΠΑΓΙΑΝΝΗ', firstName: 'ΣΤΑΥΡΟΥΛΑ', schoolTitle: 'ΛΟΓΙΣΤΙΚΗΣ&ΧΡΗΜΑΤΟΟΙΚΟΝΟΜΙΚΗΣ ΚΟΖΑΝΗ' },
  { lastName: 'ΠΑΠΑΓΙΑΝΝΗ', firstName: 'ΜΑΡΙΑ', schoolTitle: 'ΔΙΟΙΚΗΣΗΣ ΕΠΙΧΕΙΡΗΣΕΩΝ ΚΟΖΑΝΗ' },
  { lastName: 'ΠΑΠΑΓΙΑΝΝΗΣ', firstName: 'ΚΩΝΣΤΑΝΤΙΝΟΣ', schoolTitle: 'ΕΚ/ΚΩΝ ΠΟΛΙΤΙΚΩΝ ΜΗΧΑΝΙΚΩΝ ΑΣΠΑΙΤΕ' },
  { lastName: 'ΠΑΠΑΣΠΥΡΟΥ', firstName: 'ΔΗΜΗΤΡΑ', schoolTitle: 'ΕΠΙΣΤΗΜΩΝ ΠΡΟΣΧΟΛΙΚΗΣ ΑΓΩΓΗΣ & ΕΚΠ/ΚΟΥ ΣΧΕΔΙΑΣΜΟΥ ΡΟΔΟΣ' },
  { lastName: 'ΠΑΠΠΑ', firstName: 'ΛΥΔΙΑ', schoolTitle: 'ΝΟΜΙΚΗΣ ΘΕΣΣΑΛΟΝΙΚΗΣ' },
  { lastName: 'ΠΑΠΠΑ', firstName: 'ΑΓΓΕΛΙΚΗ', schoolTitle: 'ΑΓΡΟΝΟΜΩΝ & ΤΟΠΟΓΡΑΦΩΝ ΜΗΧΑΝΙΚΩΝ ΑΘΗΝΑ' },
  { lastName: 'ΠΑΠΠΑΣ', firstName: 'ΣΤΕΦΑΝΟΣ', schoolTitle: 'ΜΑΘΗΜΑΤΙΚΩΝ & ΕΦΑΡΜΟΣΜΕΝΩΝ ΜΑΘΗΜΑΤΙΚΩΝ ΗΡΑΚΛΕΙΟ' },
  { lastName: 'ΠΑΡΑΣΚΕΥΑΚΗ', firstName: 'ΕΙΡΗΝΗ', schoolTitle: 'ΜΗΧΑΝΙΚΩΝ ΠΕΡΙΒΑΛΛΟΝΤΟΣ ΧΑΝΙΑ' },
  { lastName: 'ΠΑΡΑΣΚΕΥΑΚΗ', firstName: 'ΕΥΑΓΓΕΛΙΑ', schoolTitle: 'ΟΙΚΟΝΟΜΙΚΩΝ ΕΠΙΣΤΗΜΩΝ ΙΩΑΝΝΙΝΑ' },
  { lastName: 'ΠΟΛΥΖΟΣ', firstName: 'ΔΗΜΗΤΡΙΟΣ', schoolTitle: 'ΕΥΕΛΠΙΔΩΝ (ΣΣΕ) ΟΠΛΑ' },
  { lastName: 'ΡΙΖΑΙ', firstName: 'ΜΑΡΙΟΣ-ΓΕΩΡΓΙΟΣ', schoolTitle: 'ΔΙΟΙΚΗΣΗ ΕΠΙΧΕΙΡΗΣΕΩΝ ΠΑΤΡΑ' },
  { lastName: 'ΣΙΑΝΝΑΣ', firstName: 'ΣΠΥΡΙΔΩΝ', schoolTitle: 'ΗΛΕΚΤΡΟΛΟΓΩΝ ΜΗΧΑΝΙΚΩΝ & ΤΕΧΝΟΛΟΓΙΑΣ ΥΠΟΛΟΓΙΣΤΩΝ ΠΑΤΡΑ' },
  { lastName: 'ΣΙΛΙΟΓΚΑ', firstName: 'ΕΛΙΝΑ', schoolTitle: 'ΙΑΤΡΙΚΗ ΑΘΗΝΑΣ' },
  { lastName: 'ΣΙΟΓΚΑΣ', firstName: 'ΕΥΑΓΓΕΛΟΣ', schoolTitle: 'ΜΗΧΑΝΙΚΩΝ ΠΛΗΡΟΦΟΡΙΚΗΣ ΤΕ ΑΡΤΑΣ' },
  { lastName: 'ΣΙΩΖΟΣ', firstName: 'ΧΡΗΣΤΟΣ', schoolTitle: 'ΔΙΟΙΚΗΣΗΣ ΕΠΙΧΕΙΡΗΣΕΩΝ ΠΑΤΡΑΣ' },
  { lastName: 'ΣΚΑΝΔΑΛΗΣ', firstName: 'ΑΓΓΕΛΟΣ', schoolTitle: 'ΦΥΣΙΚΗΣ ΙΩΑΝΝΙΝΑ' },
  { lastName: 'ΣΤΡΕΒΙΝΑΣ', firstName: 'ΠΑΝΑΓΙΩΤΗΣ', schoolTitle: 'ΒΙΟΛΟΓΙΑΣ ΑΘΗΝΑΣ' },
  { lastName: 'ΣΤΥΛΙΟΥ', firstName: 'ΘΕΟΔΩΡΑ', schoolTitle: 'ΕΠΙΣΤΗΜΗΣ ΦΥΤΙΚΗΣ ΠΑΡΑΓΩΓΗΣ ΑΘΗΝΑ' },
  { lastName: 'ΤΖΑΦΟΛΙΑ', firstName: 'ΠΑΡΑΣΚΕΥΗ', schoolTitle: 'ΤΕΧΝΟΛΟΓΩΝ ΓΕΩΠΟΝΩΝ ΦΛΩΡΙΝΑ' },
  { lastName: 'ΤΖΟΥΒΙΣΤΑ', firstName: 'ΜΑΡΙΑ', schoolTitle: 'ΔΙΕΘΝΩΝ & ΕΥΡΩΠΑΪΚΩΝ ΣΠΟΥΔΩΝ ΑΘΗΝΑ' },
  { lastName: 'ΤΖΟΥΚΑΣ', firstName: 'ΔΗΜΗΤΡΙΟΣ', schoolTitle: 'ΜΗΧΑΝΙΚΩΝ ΑΥΤΟΜΑΤΙΣΜΟΥ ΤΕ ΧΑΛΚΙΔΑ' },
  { lastName: 'ΤΣΑΚΟΥΜΗΣ', firstName: 'ΒΑΣΙΛΕΙΟΣ', schoolTitle: 'ΗΛΕΚΤΡΟΛΟΓΩΝ ΜΗΧ. & ΤΕΧΝΟΛΟΓΙΑΣ ΥΠΟΛΟΓΙΣΤΩΝ ΠΑΤΡΑ' },
  { lastName: 'ΤΣΑΛΑΠΑΤΗΣ', firstName: 'ΑΛΕΞΑΝΔΡΟΣ', schoolTitle: 'ΕΠΙΣΤΗΜΩΝ ΤΗΣ ΘΑΛΑΣΣΑΣ ΜΥΤΙΛΗΝΗ' },
  { lastName: 'ΤΣΙΚΟΥ', firstName: 'ΗΛΙΑ', schoolTitle: 'ΠΛΑΣΤΙΚΩΝ ΤΕΧΝΩΝ & ΕΠΙΣΤΗΜΩΝ ΤΗΣ ΤΕΧΝΗΣ ΙΩΑΝΝΙΝΑ' },
  { lastName: 'ΦΩΤΙΑΔΗΣ', firstName: 'ΟΡΕΣΤΗΣ', schoolTitle: 'ΜΗΧΑΝΙΚΩΝ ΠΛΗΡΟΦΟΡΙΚΗΣ ΤΕ ΘΕΣΣΑΛΟΝΙΚΗ' },
  { lastName: 'ΧΑΡΑΛΑΜΠΗ', firstName: 'ΔΑΝΑΗ-ΔΗΜΗΤΡΑ', schoolTitle: 'ΑΡΧΙΤΕΚΤΟΝΩΝ ΜΗΧΑΝΙΚΩΝ ΑΘΗΝΑ' },
  { lastName: 'ΧΟΥΛΙΑΡΑ', firstName: 'ΑΙΚΑΤΕΡΙΝΗ', schoolTitle: 'ΝΟΣΗΛΕΥΤΙΚΗΣ ΑΘΗΝΑ' },
  { lastName: 'ΧΟΥΛΙΑΡΑΣ', firstName: 'ΑΠΟΣΤΟΛΟΣ', schoolTitle: 'ΔΙΟΙΚΗΣΗΣ ΤΟΥΡΙΣΤΙΚΩΝ ΕΠΙΧΕΙΡΗΣΕΩΝ ΚΑΙ ΕΠΙΧΕΙΡΗΣΕΩΝ ΦΙΛΟΞΕΝΙΑΣ ΑΘΗΝΑ' },
  { lastName: 'ΧΡΗΣΤΑΚΗ', firstName: 'ΔΗΜΗΤΡΑ', schoolTitle: 'ΙΣΤΟΡΙΑΣ & ΑΡΧΑΙΟΛΟΓΙΑΣ ΡΕΘΥΜΝΟ' },
];